README.md

When the default configuration file extension was renamed from yml to yaml
it wasn't renamed through the entire README.

Fix minor README file extension inconsistency

---

src/cli/index.js
src/cli/outputMessages.js

There was an issue in bundle cli (introduced by me recently) command so it crashed when `--output` was not specified.
Also, write errors to stderr instead of stdout

fix: do not crash when `--output` is not specified

---

definitions/syntetic/inc/docs-description.md
definitions/syntetic/syntetic-1.yaml
src/__tests__/validate.test.js
src/error/__tests__/default.test.js
src/scalarsResolver.js
src/traverse.js
src/types/OpenAPIExample.js
src/types/OpenAPIExternalDocumentation.js
src/types/OpenAPIHeader.js
src/types/OpenAPIInfo.js
src/types/OpenAPILink.js
src/types/OpenAPIOperation.js
src/types/OpenAPIParameter.js
src/types/OpenAPIPath.js
src/types/OpenAPIRequestBody.js
src/types/OpenAPIResponse.js
src/types/OpenAPISchema.js
src/types/OpenAPISecuritySchema.js
src/types/OpenAPIServer.js
src/types/OpenAPIServerVariable.js
src/types/OpenAPITag.js

For now, only in 'description' field. However, this can be updated by adding 'resolvableScalars' field to the type definition for which the user wants to allow such scalars. 'resolvableScalars' is an array which must contain a list of scalars of the type for which $refs are allowed.
Now, we allow only file system references. However, it might make sense to allow also document-based $refs, like 'some/other/file.yaml#/some/node', although it will increase complexity of this module significantly.

feat: allow non-yaml $refs in scalars.

---

RULES.md
src/cli/index.js
src/visitors/rules/structural/validateAuthorizationCodeOpenAPIFlow.js
src/visitors/rules/structural/validateClientCredentialsOpenAPIFlow.js
src/visitors/rules/structural/validateImplicitOpenAPIFlow.js
src/visitors/rules/structural/validateOpenAPIOperation.js
src/visitors/rules/structural/validatePasswordOpenAPIFlow.js

The proper name is OpenAPI (not Open API).

Rename Open API to proper OpenAPI without space

---

definitions/syntetic/syntetic-1.yaml
src/__tests__/validate.test.js
src/error/__tests__/default.test.js
src/visitors/rules/semantic/checkPathParamExists.js

Rule was assuming that all of our paths were stored in a dereferenced openapi file rather than being a $ref. This should cover both cases now.

fix: checkPathParamExists rule

---

definitions/.redocly.yml
definitions/syntetic/syntetic-2.yaml
definitions/syntetic/syntetic.yaml
src/config.js

Allow to call `openapi` command in following ways:
```bash
openapi { validate | bundle } alias anotherAlias ./some_path/definition.yaml  # will lookup for aliases resolutions in the apiDefinitions field of config and then validate both aliased files and direct file path
```
For now collision is possible, e.g.:
```yaml
apiDefinitions:
public: ./definition.yaml
"private.yaml": ./another/file.yaml
```
Will cause `openapi validate private.yaml` to lookup definition in the `./another/file.yaml` even if `private.yaml` exists in current dir.

feat: support aliases in entryPoints argument

---

src/resolver.js

This was causing request to be sent with a filename instead of the URL it should go
Fixes #105

fix: use fully qualified url for XHR instead of filePath

---

src/validate.ts

I think we can safely exit(1) right when we know that document is not openapi, so that we don't need additional handling logic, but might be wrong here.

feat: handle no openapi case in openapi

---

src/redocly/index.ts

Fixes a minor bug where the help message displays references the `registry:login` command instead of the `login` command.

chore: fix help message with correct login command

---

README.md

Speccy (was, it is now unmaintained) a thin wrapper around OAS-Kit's `oas-linter`. These rules then went on to inspire the original set in Spectral.

Credit OAS-kit for original Speccy/Spectral ruleset

---

src/__tests__/__snapshots__/bundle.test.ts.snap
src/__tests__/fixtures/refs/examples.yaml
src/__tests__/fixtures/refs/openapi-with-external-refs.yaml
src/bundle.ts

Currently only the last part of the pointer (e.g. #/foo/bar -> bar) is
used for naming the component. If it's already taken, the base name of
the file reference is prepended. If it's still not unique, a sequence
number is appended to the name and warning is printed (`Two schemas are
referenced with the same name but different content.`).
The warning message is quite misleading and unnecessary because it's not
the user's fault that we used only the last part of the pointer to
generate unique component name.
To show some real-world example, let's consider file `examples.yml` with
examples for multiple types where each type may have multiple variants:
- #/Car/basic
- #/Car/electric
- #/Bike/basic
- #/Scooter/basic
The function `getComponentName()` will generate: basic, electric, …

feat: use all parts of pointer to generate uniq component name if needed

---

src/index.ts

fix: export OasDecorator and Oas3Decorator types

---

src/cli.ts

`ignored` already ends with a newline, so when no rules are ignored, two
empty lines are printed after the green validation result message.
It's quite irritating when you run multiple linters in sequence...

fix: remove extra blank line printed by printLintTotals()

---

src/__tests__/fixtures/resolve/openapi-with-back.yaml
src/__tests__/fixtures/resolve/schemas/type-a.yaml
src/__tests__/fixtures/resolve/schemas/type-b.yaml
src/__tests__/resolve.test.ts
src/resolve.ts

Closes #184 
The problem was that when we went down the ref, we don't change the absolute path in rootNodeDocAbsoluteRef and that results in failures to resolve next $refs.

fix: crash with backrefs

---

src/ref-utils.ts

The problem was that for Windows machines `openapi-cli` tried to use `/` instead of `\` for a file path splitting. Because of that, when bundling our tool used full paths as components names which lead to such cases as:
```
responses:
'200':
description: Success
content:
application/json:
schema:
$ref: >-
#/components/schemas/C:\repos\redocly-test\openapi\components\schemas\User
example:
username: user1
email: user@example.com
```
Although that is a technically valid definition, it is not what we want to get.
Also, I was able to run the `openapi-cli` development process on Windows, so it seems that the initial problem of this issue is also no more relevant.
Closes #75

fix: use platfrom specific separator

---

package.json

Bump node-fetch to 2.6.1 to address:
https://github.com/advisories/GHSA-w7rc-rwvf-8q5r

fix: node-fetch cve-2020-15168

---

README.md

We use "definition" instead of "spec" to refer to the OpenAPI documents created by users (we use "spec" to refer to the OpenAPI specification itself).

docs: fix readme usage of spec vs definition

---

__mocks__/@redocly/openapi-core.ts
packages/cli/src/commands/bundle.ts
packages/cli/src/commands/join.ts
packages/cli/src/commands/lint.ts
packages/cli/src/commands/preview-docs/index.ts
packages/cli/src/commands/push.ts
packages/cli/src/utils.ts
packages/core/src/config/builtIn.ts
packages/core/src/format/format.ts
packages/core/src/index.ts
packages/core/src/rules/common/registry-dependencies.ts
packages/core/src/rules/oas2/index.ts
packages/core/src/rules/oas3/index.ts

- export `getTotals` for usage in portal
- added some default values for `formatMessages` util function
- change `registry-dependencies` rule to be a decorator
- add built-in ruleset to be used in redocly registry (with `registry-dependencies` decorator enabled)

chore: export a util function from openapi-core and move change registry rule to decorators

---

packages/core/__tests__/fixtures/resolve/transitive/a.yaml
packages/core/__tests__/fixtures/resolve/transitive/components.yaml
packages/core/__tests__/fixtures/resolve/transitive/schemas.yaml
packages/core/__tests__/resolve.test.ts
packages/core/src/resolve.ts

Transitive $refs links spanning multiple files crashed the resolve step.

fix: fix multiple-file transitive refs resolution

---

packages/core/__tests__/__snapshots__/bundle.test.ts.snap
packages/core/__tests__/bundle.test.ts
packages/core/src/bundle.ts

`--dereferenced` was not working correctly, it did not dereference local refs.
I added a test to prevent this bug in the future.

fix:`--dereferenced` fix

---

packages/cli/src/commands/join.ts
packages/core/src/bundle.ts
packages/core/src/lint.ts
packages/core/src/resolve.ts

Parse root document using yaml/json parser regardless of file extension/mime-types.
related to https://github.com/Redocly/redoc/issues/1573

fix: always parse root document

---

packages/core/package.json

This change is allowed to resolve file system lib on the browser for libs that using openapi-core as a dependency.
Fixes the issue as: `Module not found: Can't resolve 'fs'`

chore: resolve fs lib on browser in core

---

packages/core/src/rules/common/__tests__/no-enum-type-mismatch.test.ts
packages/core/src/rules/common/no-enum-type-mismatch.ts
packages/core/src/rules/common/spec.ts
packages/core/src/rules/utils.ts
packages/core/src/typings/swagger.ts

The linter will report an error when an enum item doesn't match the corresponding schema type. However, I believe there should be an exception when an item has a value of `- null` and `nullable: true` is set. This PR reflects this exception -- adding the logic necessary to evaluate the nullable property for both `Oas2Schema` and `Oas3Schema`
https://swagger.io/docs/specification/data-models/enums/#nullable
Test was included to show that the linter should not report an error when `nullable: true` and enum items contain a `null`

[Update] enum item validation with nullable property 

---

packages/core/src/rules/common/__tests__/paths-kebab-case.test.ts
packages/core/src/rules/common/paths-kebab-case.ts

The issues were reported by a user. The message didn't make sense, so it is fixed. And it didn't catch `snake_case` but did catch camelCase`.
I added tests to the PR.

fix: Improve path kebab case message and error on snake_case

---

packages/cli/src/commands/join.ts

When tags already specify `x-displayName`, setting it with the tag's name will probably result in setting a machine-readable value instead of the intended display name.
When joining documents that have `x-displayName` defined, it takes the `name` property of the tag regardless:
Source document:
```yaml
tags:
- name: authentication
x-displayName: Authentication
description: Endpoints dealing with user authentication.
```
Resulting document:
```yaml
tags:
- name: accounts_authentication
x-displayName: authentication
description: Endpoints dealing with user authentication.
```
Expected result:
```yaml
tags:
- name: accounts_authentication
x-displayName: Authentication
description: Endpoints dealing with user authentication.
```

fix: do not overwrite 'x-displayName' of a tag on join

---

package-lock.json
packages/cli/package.json
packages/cli/src/index.ts

We were using `yargs@17.0.0-candidate.6` for completion feature. Now that stable `yargs@17.0.1` is released, it's time to update.

chore: update yargs version from rc to stable

---

__mocks__/@redocly/openapi-core.ts
packages/cli/src/__mocks__/utils.ts
packages/cli/src/__tests__/commands/bundle.test.ts
packages/cli/src/commands/bundle.ts
packages/cli/src/index.ts

Bundle command doesn't execute the validation rules.
Added optional param --lint to bundle command to 
close https://github.com/Redocly/openapi-cli/issues/291
https://github.com/Redocly/marketing-site-portal/pull/348
```zsh
~$ openapi bundle -o dist.yaml --lint
openapi.yaml:
1:1  error    spec              The field `paths` must be present on this level.
1:1  error    no-empty-servers  Servers must be present.
3:3  warning  info-description  Info object should contain `description` field.
6:5  warning  info-license-url  License object should contain `url` field.
❌ Validation failed with 2 errors and 2 warnings.
run with `--generate-ignore-file` to add all problems to ignore file.
bundling ~/openapi.yaml...
📦 Created a bundle for ~/openapi.yaml at dist.yaml 16ms.
```

feat: add optional --lint param to bundle command

---

packages/core/src/config/__tests__/fixtures/plugin-config.yaml
packages/core/src/config/__tests__/fixtures/plugin.js
packages/core/src/config/__tests__/resolve-plugins.test.ts
packages/core/src/config/config.ts

Clone plugin structures that are being changed while importing.
`loadConfig()` can be called more than once, which results in preprocessors, rules and  decorator rules in plugins being prefixed with the plugin id more than once.
This happens when running `openapi preview-docs` and then changing the config file, for example.
This fixes #287.
I've included a test that demonstrates the issue, as a separate commit. Without the other commit in this PR, the test fails with:
```
FAIL  packages/core/src/config/__tests__/resolve-plugins.test.ts
● resolving a plugin › should prefix preprocessor names with the plugin id
expect(received).toHaveProperty(path)
Expected path: "test-plugin/description-preprocessor"
Received path: []
Received value: {"test-plugin/test-plugin/description-preprocessor": …
```

Clone plugin structures rather than change in-place

---

packages/cli/src/__mocks__/utils.ts

Tests failing due to bad `utils.dumpBundle` mock return value type

fix: utils.dumpBundle testing mock

---

packages/core/__tests__/walk.test.ts
packages/core/src/config/config.ts

Plugin type extensions are the only remaining place that doesn't support
OpenAPI 3.1.0 documents.
Fixes #314
I've parametrized the existing type extensions test. The fact that the test
adds webhook support (something OAS 3.1 has explicit support for now) may be
slightly silly, but the test is no less valid for it.
- (I don't think this is applicable here)

Support OAS 3.1 in type extensions

---

packages/core/src/format/codeframes.ts
packages/core/src/index.ts

[VS Code extension](https://github.com/Redocly/openapi-vs-code) requires exports of some additional functions

chore: additional exports for vs code extension

---

packages/core/src/bundle.ts
packages/core/src/walk.ts

on vs code extension, we need the types of file reference.  We use it in the autocomplete.

feat: return type of reference in bundleDocument

---

docs/commands/index.md

Removed redundancy from the OpenAPI CLI commands home page. Made the page more concise.

docs: OpenAPI CLI commands home page

---

packages/cli/src/__tests__/utils.test.ts
packages/cli/src/commands/preview-docs/preview-server/preview-server.ts
packages/cli/src/utils.ts

The file `packages/cli/src/commands/preview-docs/preview-server/preview-server.ts` contains a security defect that allows directory traversal of the complete file path on a server and the download of files via query parameters on the request URI.
Example: 
http://localhost:8080/jsp/help-sb-download.jsp?sbFileName=../../../../.redocly.yaml
Applying a `request.url.split('?')[0]` at the start of the preview server function has stopped this from occurring.
https://github.com/Redocly/openapi-cli/blob/master/packages/cli/src/commands/preview-docs/preview-server/preview-server.ts#L99
The usage of `path.resolve()` on this line can result in arbitrary download of any file on the server if query params are exploited.
Fix tested manually

Strip query parameters from request URL in preview server

---

.dockerignore
Dockerfile

As described in #272, running `preview-docs` in a `redocly/openapi-cli` Docker container will cause the container to crash instantly. This is not an issue with the Docker image. The problem lies in the Webpack build process that is causing the following `TypeError`. 
Running the following command `npm run bundle && node dist/bundle.js preview-docs resources/pets.yaml` will result in the following error as well.
```
TypeError: s is not a constructor
at Object.t.startWsServer (/bin/openapi-cli:49:129227)
at Object.<anonymous> (/bin/openapi-cli:49:21717)
at Generator.next (<anonymous>)
at o (/bin/openapi-cli:49:19069)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
---
Currently Webpack will load `simple-websocket` as an empty module. This is introduced in PR #177, …

build: fix preview-docs command in Docker

---

package-lock.json
packages/core/package.json

bumped ajv version to ^8.6.4

---

.github/workflows/deploy.yaml
.github/workflows/dockerhub.yaml

The **CD to Docker Hub** workflow often fails on the first run. 
**Possible reason:** a race condition with the **CD to NPM & AWS S3** workflow, deployment part:
In case `packages/cli/package.json` contains the just releasing version of the `@redocly/openapi-core` as dependency,
it tries to load it from npm before it is published. 
**Solution:** Make the **CD to Docker Hub** call as the last job of the **CD to NPM & AWS S3** workflow.

chore: made the dockerhub workflow a consequtive step after publishing

---

packages/core/__tests__/__snapshots__/bundle.test.ts.snap
packages/core/__tests__/bundle.test.ts
packages/core/__tests__/fixtures/refs/definitions.yaml
packages/core/__tests__/fixtures/refs/external-request-body.yaml
packages/core/__tests__/fixtures/refs/externalref.yaml
packages/core/__tests__/fixtures/refs/rename.yaml
packages/core/__tests__/fixtures/refs/requestBody.yaml
packages/core/__tests__/fixtures/refs/simple.yaml
packages/core/__tests__/fixtures/refs/vendor.schema.yaml
packages/core/src/bundle.ts

This is a fix for a `openapi bundle` command when there are external references.
**Prerequisites:**
`definition.yaml`
```yaml
openapi: 3.0.0
info:
title: My API
description: It ain't so wonderful, but at least it's mine.
version: '1.0'
contact:
email: me@theintenet.com
name: me
tags:
- name: tag1
servers:
- url: 'https://dev01.internet.com/api/v0'
description: Development server.
components:
schemas:
vendor:
$ref: ./vendor.schema.yaml
myvendor:
$ref: ./vendor.schema.yaml
```
`vendor.schema.yaml`
```yaml
title: vendor
type: object
description: Vendors
properties:
key:
type: string
description: System-assigned key for the vendor.
readOnly: true
id:
type: string
description: |
Unique identifier of the vendor.
You must specify a unique vendor ID when creating a vendor unless document …
```

fix: inline dereferenced schema when original schema name matches resolved schema name

---

.github/workflows/deploy-s3-sandbox.yaml
.github/workflows/deploy.yaml
.github/workflows/tests.yaml

7.7.6 version of npm fails to install dependencies in github actions. Locking to older version 7.23.0

lock npm version to 7.23.0 in github actions

---

.github/workflows/deploy-s3-sandbox.yaml
.github/workflows/deploy.yaml
.github/workflows/tests.yaml
__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

`v1.0.0-beta.68`
Changelog:
- chore: made the dockerhub workflow a consequtive step after publishing ([commit](https://github.com/Redocly/openapi-cli/commit/bfc8473431d00b3ee9ec5350b3b5440b451ea4a8))
- fix: hot reloading + page refresh for section pagination ([#436](https://github.com/Redocly/openapi-cli/pull/436))
- fix: inline dereferenced schema when original schema name matches resolved schema name ([#439](https://github.com/Redocly/openapi-cli/pull/439))
- fix: resolve fetching of hosted schema on windows ([#441](https://github.com/Redocly/openapi-cli/pull/441))
- fix: should not throw error when server url is root ([#448](https://github.com/Redocly/openapi-cli/pull/448))

chore: 1.0.0-beta.68

---

__tests__/lint/no-path-trailing-slash-off/.redocly.yaml
__tests__/lint/no-path-trailing-slash-off/openapi.yaml
__tests__/lint/no-path-trailing-slash-off/snapshot.js
packages/core/src/rules/common/__tests__/paths-kebab-case.test.ts
packages/core/src/rules/common/paths-kebab-case.ts

Fixes https://github.com/Redocly/openapi-cli/issues/465
https://github.com/Redocly/openapi-cli/issues/465

fix: paths-kebab-case does not allow trailing slash

---

docs/changelog.md
packages/core/src/redocly/__tests__/redocly-client.test.ts
packages/core/src/redocly/index.ts

Backward compatibility of `REDOCLY_DOMAIN` was broken in beta.70 for EU region. Fixing it back.

hotfix: fix REDOCLY_DOMAIN backward compatibility

---

docs/changelog.md
packages/core/src/redocly/index.ts

We need to save old config key to support old portal versions.

fix: fix another backward compatibility issue with regions

---

docs/commands/preview-docs.md
packages/cli/src/commands/preview-docs/index.ts
packages/cli/src/commands/preview-docs/preview-server/preview-server.ts
packages/cli/src/commands/preview-docs/preview-server/server.ts
packages/cli/src/index.ts

closes https://github.com/Redocly/openapi-cli/issues/474

feat: add host arg to preview-docs cli command

---

packages/core/src/bundle.ts
packages/core/src/index.ts

Export ```mapTypeToComponent``` function in order to have type to component field mapping (needed by vs-code extension)

chore: export mapTypeToComponent function

---

packages/cli/src/__tests__/commands/bundle.test.ts
packages/cli/src/commands/bundle.ts
packages/cli/src/commands/lint.ts

When cli is spawned by another node process process.exit does not allow stdout pipe to flush the remaining chunk of data so we get an invalid json.
See https://github.com/nodejs/node-v0.x-archive/issues/3737#issuecomment-19156072 for more details.
Discovered during local testing.

fix: defer process exit to allow STDOUT pipe to flush

---

packages/cli/src/commands/split/__tests__/fixtures/spec.json
packages/cli/src/commands/split/__tests__/index.test.ts
packages/cli/src/commands/split/index.ts

fix: https://github.com/Redocly/openapi-cli/issues/484
I'll try to add some unit tests for this case since there is not any for this file so far.

fix: backslashes in $refs to paths on split command from windows

---

__tests__/bundle/bundle-lint-format/checkstyle-format-snapshot.js
__tests__/index.test.ts
docs/commands/bundle.md
docs/commands/lint.md
packages/cli/src/index.ts
packages/core/src/format/format.ts

Add another format for linting: Checkstyle. Can be used to pipe linting results into Jenkins, for example. Implementation is adapted from the one [found in ESLint](https://github.com/eslint/eslint/blob/v8.6.0/lib/cli-engine/formatters/checkstyle.js).

feat: add checkstyle as new lint format

---

packages/core/src/rules/__tests__/hide-internals.test.ts
packages/core/src/rules/common/remove-x-internal.ts

fix: remove-x-internal decorator doesn't remove references to x-internal components

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
__tests__/index.test.ts

- remove version in bundle-lint-format test - json format
- add `cleanUpVersion` function to print in Serializer - all snapshots printed without package version

fix: cleanup version in e2e tests

---

__tests__/bundle/bundle-remove-unused-components/oas2/openapi.yaml
__tests__/bundle/bundle-remove-unused-components/oas2/ref.yaml
__tests__/bundle/bundle-remove-unused-components/oas2/remove-unused-components-snapshot.js
__tests__/bundle/bundle-remove-unused-components/oas3/openapi.yaml
__tests__/bundle/bundle-remove-unused-components/oas3/ref.yaml
__tests__/bundle/bundle-remove-unused-components/oas3/remove-unused-components-snapshot.js
packages/core/src/bundle.ts
packages/core/src/resolve.ts
packages/core/src/rules/oas2/remove-unused-components.ts
packages/core/src/rules/oas3/remove-unused-components.ts
packages/core/src/walk.ts

fix: remove-unused-components strips remotely referenced components

---

packages/cli/src/commands/preview-docs/preview-server/oauth2-redirect.html
packages/cli/src/commands/preview-docs/preview-server/preview-server.ts

fix: oauth2-redirect.html is absent when served by preview-docs command #509

fix: oauth2-redirect.html is absent when served by preview-docs command #509

---

packages/core/src/config/config.ts
packages/core/src/redocly/__tests__/redocly-client.test.ts
packages/core/src/redocly/index.ts
packages/core/src/redocly/redocly-client-types.ts

Added `getAllTokens` method to `RedoclyClient` class to avoid code duplication of finding `.redocly-config.json` file, reading tokens from there and taking proper token field.

chore: add getAllTokens method to RedoclyClient

---

packages/core/src/config/__tests__/load.test.ts
packages/core/src/config/load.ts
packages/core/src/index.ts

[Pitch: change .redocly.yaml config structure](https://intranet.redoc.ly/roadmap/tooling/2022-02/redocly-yaml/)
Introduces `redocly.yaml` file name.

feat: introduce redocly.yaml

---

__tests__/lint/oas3.1-error/snapshot.js
packages/core/src/rules/common/__tests__/spec.test.ts
packages/core/src/rules/common/spec.ts
packages/core/src/types/oas3.ts
packages/core/src/utils.ts

OpenAPI CLI should detect Parameters without schema or content fields while the OpenAPI specification states that one of these fields MUST be specified.
Fixes #568 
Fixes #570 
Tested locally
N/a

fix: detect parameters without schema or content fields

---

packages/core/src/redocly/index.ts

The previous release crashes client-side builds (e.g. in our portal) because it contains `process.env` assignment which is converted to a const by DefinePlugin.
https://github.com/Redocly/redocly-portal/runs/5487874186?check_suite_focus=true#step:7:100

fix: terser crash in client-site bundles due to process.env assignment

---

packages/core/src/config/config.ts

At the moment, when trying to log in to a lab environment, the request is always sent to the `api.redocly.com/registry`. It happens because there are no 'lab' regions in `ALLOWED_DOMAINS` so OpenapiCLI uses default 'us' region.

fix: use correct domain when logging to labs

---

packages/core/src/config/config.ts
packages/core/src/config/load.ts

- Fixes crash when there's an empty [.]redocly.yaml file
- Fixed some types
- Applied Prettier

hotfix: do not crash on empty redocly.yaml

---

packages/core/src/__tests__/lint.test.ts
packages/core/src/types/redocly-yaml.ts

Update types used to lint .redocly.yaml according to new config file structure

fix: update .redocly.yaml types

---

__tests__/lint/info-contact--deprecated-format/snapshot.js
__tests__/lint/no-enum-type-mismatch-error-recommended-config/snapshot.js
__tests__/lint/no-undefined-server-variable-error-recommended-config/snapshot.js
package-lock.json
packages/core/src/config/config.ts

Since we released the new configuration format we put deprecation warnings so users can start migration.
https://redocly.com/docs/cli/configuration/configuration-file/

chore: add deprecation warnings for the old configuration format

---

packages/core/__tests__/__snapshots__/bundle.test.ts.snap
packages/core/__tests__/ref-utils.test.ts
packages/core/src/ref-utils.ts

Fixes the issue when `foo.bar.baz.v1.yaml`, `foo.bar.qux.v1.yaml` and `foo.quux.quuz.v1.yaml` would get folded into the components collection as foo-1, foo-2 and foo-3 - along with a load of "duplicate name" errors.
This happened because it treated everthing after the **first** dot as a file extension. Now it matches the **last** dot of the filename.
closes #560

fix: improper handling of filenames with multiple dots

---

docs/resources/built-in-rules.md
docs/resources/rules/assertions.md

Add docs for the assertions feature. A few notes:
- I did not try out the feature yet.
- There are "TODO"s inside of the docs. Please look at the PR and find/comment.
- I omitted the `sortOrder` for now and would like to discuss it a bit further.
- In code: rename `description` to `message` for consistency with the naming throughout OpenAPI cli.
- In code: I think we should add support for `suggest` too (like we have that support in our built-in rules as well as custom rules).
This moves the bulk of the assertions docs to a stand-alone page.
In general, each rule should have its own page, but that will take a good deal of time to set up. There is no way this content can go inside of the built-in rules page, so instead I added a link to it from there. …

docs: add assertions docs

---

docs/commands/push.md
package.json
packages/cli/package.json
packages/cli/src/__tests__/commands/push-region.test.ts
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts
packages/cli/src/index.ts

This PR does two main things: 
* Adds `--skip-decorator` option to the `push` command
* Adds support for multiple API definitions in `.redocly.yaml` using `getMergedConfig` function
Additionally, a small change that makes sure `npm run e2e` only runs tests in the `__tests__` directory in the root of the project.
Resolves https://github.com/Redocly/workflows/issues/1387

Feat: Skip decorator option for push command

---

packages/core/src/config/config.ts

Push command skips any dependencies because the merged config loses the original config filename and there is a check here: https://github.com/Redocly/openapi-cli/blob/hotfix-get-merged-config/packages/cli/src/commands/push.ts#L224
Reported by customer.

hotfix: fix getMergedConfig to keep config file location

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

feat: lint oas3.1 unevaluatedProperties as boolean #621  (closes #620)
chore: remove "_" from types for consistency (#636)
chore: improve deploy-local [#639](https://github.com/Redocly/openapi-cli/pull/639)

chore: v1.0.0-beta-94

---

docs/resources/built-in-rules.md

All of the built-in rules are alphabetized except for `assertions`.

docs: alphabetize built-in rules

---

packages/core/package.json
packages/core/src/config/config-resolvers.ts
packages/core/src/config/config.ts
packages/core/src/resolve.ts

Resolves node dependencies issues in browser environment when using OpenAPI core with Webpack 5. 
Also related to https://github.com/Redocly/redoc/issues/1820

chore: update config to use with Webpack 5

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

- Fixed resolving scalar values in asserts (#646) 
- Added fixtures for resolving remote configs (#654)
- Added support for files in Redocly config `extends` section (#616)
- Added codeclimate formating for lint command (#669)
- Updated config to use with Webpack 5 (#671)

chore: bump to v1.0.0-beta.95

---

Dockerfile

Fix: Docker fails when using the wrong folder name (old name of `openapi-cli`).
https://github.com/Redocly/redocly-cli/runs/6325051442?check_suite_focus=true

chore: fix docker using openapi-cli

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json
packages/core/src/utils.ts

> Pitch Redoc 2.0
The previous **minimatch** version uses **node** `path` package which propagates further and causes issues when using `openapi-core` with Webpack 5. 
Also fixes issue with `URL` not recognised as a standard.

chore: update dependencies to eliminate using path in minimatch and fix not recognising URL as a standard

---

docs/commands/push.md
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts
packages/cli/src/index.ts
packages/core/src/redocly/registry-api-types.ts
packages/core/src/redocly/registry-api.ts

Added public option for push command. Make API registry public accessible.
Resolve https://github.com/Redocly/workflows/issues/1958

feat: added --public option for push command

---

packages/cli/src/commands/preview-docs/preview-server/preview-server.ts

This PR fixes preview server hot reloads for the `openapi-cli` package global installation. 
As @nbourguig has pointed out, the issue was introduced with https://github.com/Redocly/openapi-cli/pull/347. The check only allowed files from the `CWD` to be served by the preview server while the scripts needed for hot reload were in the global installation directory. Now the check only applies to arbitrary files.
closes https://github.com/Redocly/openapi-cli/issues/538

fix: preview server hot reload

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

- Chore: Docker fails when using the wrong folder name (old name of openapi-cli) https://github.com/Redocly/redocly-cli/pull/677
- Fix: Fixed issue with process.* in core package https://github.com/Redocly/redocly-cli/pull/541
- Chore: Update dependencies to eliminate using path in minimatch and fix not recognising URL as a standard https://github.com/Redocly/redocly-cli/pull/674
- Feature: Added `--public` option for `push` command https://github.com/Redocly/redocly-cli/pull/667
- Fix: Fixed preview server hot reloads for the openapi-cli package global installation. https://github.com/Redocly/redocly-cli/pull/673
- Feature: Changed assertions syntax to: `assert/{assert name}` https://github.com/Redocly/redocly-cli/pull/662

chore: bump to v1.0.0-beta.97

---

docs/resources/built-in-rules.md
packages/core/src/__tests__/utils.test.ts
packages/core/src/rules/common/response-contains-header.ts
packages/core/src/rules/oas2/__tests__/response-contains-header.test.ts
packages/core/src/rules/oas2/__tests__/response-contains-property.test.ts
packages/core/src/rules/oas2/index.ts
packages/core/src/rules/oas2/response-contains-property.ts
packages/core/src/rules/oas3/__tests__/response-contains-header.test.ts
packages/core/src/rules/oas3/__tests__/response-contains-property.test.ts
packages/core/src/rules/oas3/index.ts
packages/core/src/rules/oas3/response-contains-property.ts
packages/core/src/utils.ts

Closes #390 & #389 respectively

feat: `response-contains-header` & `response-contains-property` built-in rules

---

.github/workflows/tests.yaml
package.json

Coverage action do not fail when UT fail

fix: coverage action not fail when UT fail

---

docs/quickstart.md

docs: fix typo in cli quickstart

---

packages/core/src/rules/common/__tests__/scalar-property-missing-example.test.ts
packages/core/src/rules/common/scalar-property-missing-example.ts

`scalar-property-missing-example` rule was reporting an error for falsy values like '', 0, false in the example.
N/a

fix: allow scalar property with falsy values

---

packages/cli/src/commands/push.ts

Push shows an error when batch-id isn't added

fix: push shows an error when batch-id isn't added

---

docs/resources/built-in-rules.md

Incorrect `response-contains-property` rule example.
https://redocly.com/docs/cli/resources/built-in-rules/#response-contains-property

docs: fix incorrect response-contains-property example

---

packages/core/package.json

Ignore `collorette` for browser build in openapi-core. It should be removed after finishing https://github.com/Redocly/redocly-cli/issues/539. 
This package is used in `redoc` and also effect it.

chore: add colorette to ignore browser build

---

packages/core/src/types/redocly-yaml.ts

`scalar-property-missing-example` rule has been missing in Config types.
https://redocly.com/docs/cli/resources/built-in-rules/#scalar-property-missing-example

chore: add scalar-property-missing-example rule to the config types

---

.github/workflows/tests.yaml

Fixes github action failing on MR from forks due to lacking permissions by splitting coverage report into a separate always-passing job.

chore: move coverage report into a separate job

---

packages/core/src/decorators/__tests__/filter-out.test.ts
packages/core/src/decorators/common/filters/filter-helper.ts

- Fix use of if guards on filtering in and out some nodes from an openapi file. 
- The use of **! operator*** for checking whether a value was undefined also checked out false (boolean) and null values. What made it impossible to use those values for filtering nodes out of the file.
- As a border effect, this problem didn't occur while filtering **in** properties that had these values (false/null) but not for the "proper reason".
- Explicitly use **"=== undefined"**  to verify if the structure hasn't been given as a parameter to the function call instead of using the **! operator** 
- This allows the use of both false and null values to filter nodes in or out an openapi file 
[Filter-out does not filter out when value is set to false (bool) …

Fix : Filter-out does not filter out when value is set to false (bool) #753

---

__tests__/commands.test.ts
__tests__/join/multiple-tags-in-same-files/bar.yaml
__tests__/join/multiple-tags-in-same-files/foo.yaml
__tests__/join/multiple-tags-in-same-files/snapshot.js
packages/cli/src/commands/join.ts

After the `join` command tags can be duplicated which cause issue with bad display on Reference Docs for example. This should be fixed.
resolve #755
Definition Bar:
Definition Foo:
After fix:

fix: fix multiple tags duplication

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Bump version to `v1.0.0-beta.104`.
Release includes:
- [INTERNAL] chore: add colorette to ignore browser build (#744)
- [INTERNAL] chore: add `scalar-property-missing-example rule` to the config types (#749)
- [INTERNAL] chore: fix typing and update docs on `ctx.resolve` (#748)
- [INTERNAL] chore: move coverage report into a separate job (#760)
- Fix : Filter-out does not filter out when value is set to false (bool) (#754 / Issue  #753)
- Fix: Multiple tags duplication (#761 / Issue #755)
Closes #753

chore: v1.0.0-beta.104

---

docs/commands/bundle.md

`--remove-unused-components` flag was missing from the docs.

docs: add missing --remove-unused-components flag docs

---

docs/resources/rules/assertions.md

The examples weren't working. This fixes the issue.

docs: fix ref assertion examples

---

__tests__/lint/no-enum-type-mismatch-error/snapshot.js
packages/core/src/rules/common/__tests__/no-enum-type-mismatch.test.ts
packages/core/src/rules/common/no-enum-type-mismatch.ts

The current message is wrong, because in 3.1 you can define multiple types. The behavior works fine though except for `type: any` and an issue is opened for that (#786).
Tests were adjusted as well.

fix: fix enum type mismatch message

---

package.json
packages/cli/src/__mocks__/utils.ts
packages/cli/src/__tests__/commands/bundle.test.ts
packages/cli/src/__tests__/commands/lint.test.ts
packages/cli/src/commands/lint.ts
packages/cli/src/utils.ts

Resolve an issue where we always return a 0 exit code, even when the result is not successful. 
Therefore, we decided to return code 1 in the handleError function to cover move cases then mentioned in the initial issue.
Fixed #547
Tested locally.
N/a

fix: incorrect return codes when exit with error

---

__tests__/lint-config/invlid-lint-config-saverity/snapshot.js
__tests__/split/missing-outDir/snapshot.js
docs/commands/bundle.md
docs/commands/join.md
docs/commands/lint.md
docs/commands/preview-docs.md
docs/commands/push.md
docs/commands/split.md
docs/commands/stats.md
packages/cli/src/__mocks__/utils.ts
packages/cli/src/__tests__/commands/bundle.test.ts
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/__tests__/commands/lint.test.ts
packages/cli/src/__tests__/commands/push-region.test.ts
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/bundle.ts
packages/cli/src/commands/join.ts
packages/cli/src/commands/lint.ts
packages/cli/src/commands/preview-docs/index.ts
packages/cli/src/commands/push.ts
packages/cli/src/commands/split/__tests__/index.test.ts
packages/cli/src/commands/split/index.ts
packages/cli/src/commands/stats.ts
packages/cli/src/index.ts
packages/cli/src/types.ts
packages/cli/src/utils.ts
packages/core/README.md
packages/core/src/config/utils.ts

Closes https://github.com/Redocly/redocly-cli/issues/697
Please pay special attention to [this removed line](https://github.com/Redocly/redocly-cli/pull/802/files#diff-95a484b5e45f4ec9a4b5e98e2b043470cb9b4d8c3f1a70a44710b49aa7e35d65L143) and to [this changes in preivew-docs README](https://github.com/Redocly/redocly-cli/pull/802/files#diff-21d006e0ab455bc4afc351da05020cee4d8420fcdcc6650362f493864771b9adR16-R26).
---
---

chore: rename 'entrypoints' into 'apis'

---

.github/CONTRIBUTING.md
packages/core/src/rules/__tests__/utils.test.ts
packages/core/src/rules/oas3/__tests__/spec/spec.test.ts
packages/core/src/rules/utils.ts

Add tests to cover part of rules utils.
Originally started with #786 which was erroneous because `type: any` doesn't exist any longer.
This revealed we missed an `integer` case for one method: `oasTypeOf`.
I added that and covered it with tests.
One open question:
```ts
export function missingRequiredField(type: string, field: string): string {
return `${type} object should contain \`${field}\` field.`;
}
```
Is the correct word `should` (as is) or `must`? For example, 
> Tag object should contain `description` field.
> Tag object must contain `description` field.

chore: add tests for rules utils

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Bump Redocly CLI & Openapi Core to v1.0.0-beta.106.
Here're the changes:
[INTERNAL] chore: add tests for rules utils (#789)
[INTERNAL] chore: rename 'entrypoints' into 'apis' (#802)
fix: incorrect return codes when exit with error (#798)
[INTERNAL] chore: update issue templates (#795)
[INTERNAL] chore: Setup and run Prettier  (#797)
[INTERNAL] chore: rename 'lint' to 'styleguide' (#790)
[INTERNAL] fix: fix enum type mismatch message (#784)
[INTERNAL] chore: test for cli package (#773)
[INTERNAL] chore: fix filenames for license rules (#783)
[INTERNAL] docs: fix ref assertion examples (#777)
This should be merged alongside the release: https://github.com/Redocly/redocly-cli/pull/791.

chore: v1.0.0-beta.106

---

docs/changelog.md

- Each entry is a full-sentence description with punctuation (full-stop).
- `Features` are different from `Changes` which are breaking.
- #820

docs: fix changelog for consistency

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

What's included in this release: 
**Changes**
- Add browser support for `openapi-core` https://github.com/Redocly/redocly-cli/pull/811
- Allow accessing `config` field in subclasses extending BaseResolver class https://github.com/Redocly/redocly-cli/pull/810
- Ability to create config (e.g. `redocly.yaml`) from string or object https://github.com/Redocly/redocly-cli/pull/809
- Renamed `no-servers-empty-enum` to `no-server-variables-empty-enum` and fixed incorrect docs of `no-empty-enum-servers` https://github.com/Redocly/redocly-cli/pull/813
**Fixes**
- Fixed docs for `no-server-example.com` https://github.com/Redocly/redocly-cli/pull/813
- Incorrect schema description dereferenced https://github.com/Redocly/redocly-cli/pull/814
**[INTERNAL]**
- …

chore: v1.0.0-beta-108

---

__tests__/bundle/bundle-description-long/.redocly.yaml
__tests__/bundle/bundle-description-long/snapshot.js
__tests__/bundle/bundle-description-long/test.yaml
__tests__/bundle/tag-description-override/snapshot.js
__tests__/commands.test.ts
packages/cli/src/utils.ts

Fix #480. Just remove limit of line width

fix: leave multiline strings in literal mode

---

packages/core/src/types/oas3.ts

The check was missing for header object.
Fixes https://github.com/Redocly/redocly-cli/issues/801

fix: require schema or content for header object

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

- Added rfc7807 problem details rule. (#816)
- Improved error messages by adding `referenced from` information. (https://github.com/Redocly/redocly-cli/pull/835)
- Added a rule for component map names validation. (#815)
- Added a new `--format` option: `summary`. (#860)
- Fixed an issue with multi-line strings in literal mode. (#822)
- Fixed an issue with multi-line Markdown with Windows-style new lines. (#827)
- Fixed a Header object spec to require `content` or `schema`. (#830)
- Fixed a error message for `operation-4xx-response` rule (closes https://github.com/Redocly/redocly-cli/issues/840).
- Fixed an issue with `paths` not being correctly handled by the `join` command. (#778)
- Fixed the `operation-security-defined` rule to check the security on the root and in each operation. …

chore: v1.0.0-beta.109

---

package-lock.json
packages/cli/package.json

Lock version for styled-component inside `redocly/cli`

chore: fix version of styled-component

---

packages/core/src/rules/common/__tests__/operation-2xx-response.test.ts
packages/core/src/rules/common/__tests__/operation-4xx-response.test.ts
packages/core/src/rules/common/operation-2xx-response.ts
packages/core/src/rules/common/operation-4xx-response.ts
packages/core/src/rules/common/response-contains-header.ts
packages/core/src/rules/oas3/__tests__/response-contains-header.test.ts

In the `response-contains-header` rule we need to force toLowerCase on comparison for accurate results. 
Closes  #824
Locally.
N/a

fix: response-contains-header force toLowerCase on comparison

---

packages/core/src/rules/common/__tests__/path-params-defined.test.ts
packages/core/src/rules/common/path-params-defined.ts

If parameters ware not defined in the other operation but exist in first lint did not catch error.
For example 
```yaml
paths:
/case/{a}:
get:
parameters: 
- name: a
in: path
schema: 
type: number 
summary: Case GET 
description: Should not fail cause parameters exist
responses:
'200':
description: Successful operation
post: 
summary: Case POST
description: Should fail cause no parameters
responses:
'200':
description: Successful operation
```
Closes #211 
Now it throw appropriate error

fix: path parameter not defined

---

packages/cli/src/index.ts

There was added [`keep-url-references`](https://github.com/Redocly/redocly-cli/pull/688) flag for the `bundle` command but not as argument for cli
Close #888

fix: add keep-url-references 

---

packages/cli/src/__tests__/utils.test.ts
packages/cli/src/utils.ts
resources/.redocly.yaml

If `redocly-cli lint` was run with path to the file as argument it was not detecting proper overrides from `apis` config.
Found it while fixing https://github.com/Redocly/redocly-cli/issues/899
Added a unit test.

fix: detect api from the list by the root file match

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Bump version to `v1.0.0-beta.113`.
The release includes:
- $anchors in openapi documents are not properly parsed (#836)
- Added list types (https://github.com/Redocly/redocly-cli/pull/928)
- Undefined process.cwd in browser environment (#922)
- Do not add the recommended ruleset fallback when there is a config (#923)
-  Ignore discriminator error (#931)
- Nullable in schema object must have a type sibling (#938)

chore: v1.0.0-beta.113

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

v1.0.0-beta.115 release:
- feat: add support for any type in assertions (#948)
- fix: outdated Docker image name (#949)
- chore: fix assertion messages grouping (#950)
- chore: remove orphaned git submodule public_api_docs (#934)

chore: v1.0.0-beta.115

---

packages/core/src/rules/oas3/__tests__/spec-components-invalid-map-name.test.ts
packages/core/src/rules/oas3/spec-components-invalid-map-name.ts

Fix an issue where the rule `spec-components-invalid-map-name` is not applied for all examples and adjust the logic behind the rule in general.
Resolves #959
Locally.
N/a

fix: spec-components-invalid-map-name not applied for all examples

---

packages/core/src/rules/common/assertions/__tests__/asserts.test.ts
packages/core/src/rules/common/assertions/asserts.ts
packages/core/src/rules/common/assertions/utils.ts

Fix an issue with asserts not accepting the List nodes properly (e.g TagList).
Allow sortOrder to sort string values in a case-insensitive manner. 
Throw a message if the user wants to sort objects without defining a property to sort by.
Locally.
N/a

chore: change sortOrder logic

---

packages/core/src/rules/common/__tests__/spec.test.ts
packages/core/src/types/index.ts
packages/core/src/types/oas3_1.ts

Add support for `x-logo` type to the 3.1 spec version. 
Allow additional properties for the SpecExtension type. 
https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1672741829392659
Locally.
N/a

fix: spec rule error on extension additional properties

---

packages/core/src/rules/__tests__/no-unresolved-refs.test.ts
packages/core/src/types/index.ts

Resolve an issue where refs aren't resolved inside specification extensions while linting.
https://redoc-ly.slack.com/archives/C02UHE7EL3E/p1672777257007459
Locally
N/a

fix: resolve refs inside spec extensions

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

v1.0.0-beta.120 release:
- fix: resolve refs inside spec extensions (#981)
- fix: resolve nested refs inside spec extensions (#985)
- chore(deps): bump json5 from 2.2.1 to 2.2.3 (#980)

chore: v1.0.0-beta.120

---

docs/rules/operation-2xx-response.md
docs/rules/operation-4xx-response.md
packages/core/src/rules/common/__tests__/operation-2xx-response.test.ts
packages/core/src/rules/common/__tests__/operation-4xx-response.test.ts
packages/core/src/rules/common/operation-2xx-response.ts
packages/core/src/rules/common/operation-4xx-response.ts
packages/core/src/rules/utils.ts

In terms of our [operation-4xx-response/](https://redocly.com/docs/cli/rules/operation-4xx-response/) rule we treat webhooks the same as path items (as it's intended by the spec).
However, webhooks ofter times are treated differently than path items so it makes sense to provide an option to exclude them from the rule.
Closes #955 
Locally.
N/a

feat: add an option to include webhooks to operation-4xx-response rule

---

docs/guides/index.mdx

The guide was added to the sidebar (in the linked PR). This PR adds the guide to the index list (tiles) on the https://redocly.com/docs/cli/guides/ page
Related to Redocly/marketing-site-portal#1032

docs: add missing guide to the list on the cli guides page

---

packages/cli/src/commands/build-docs/utils.ts
packages/cli/src/commands/preview-docs/index.ts
packages/cli/src/commands/push.ts
packages/cli/src/index.ts
packages/core/src/__tests__/lint.test.ts
packages/core/src/config/__tests__/config.test.ts
packages/core/src/config/__tests__/utils.test.ts
packages/core/src/config/config.ts
packages/core/src/config/types.ts
packages/core/src/config/utils.ts
packages/core/src/rules/utils.ts
packages/core/src/types/redocly-yaml.ts
packages/core/src/utils.ts

A new product we are releasing has a similar but different configuration format. For example, instead of features.openapi it is configured in theme object with property openapi object. We need to make them inline with each other.
Closes #982
Locally.
N/a

chore: rename features.openapi and features.mockServer to theme

---

docs/changelog.md
docs/commands/push.md
docs/configuration/api.yaml
docs/configuration/index.mdx
docs/configuration/schema.yaml

docs: rename features.openapi and features.mockServer in config

---

__tests__/bundle/info-override/.redocly.yaml
__tests__/bundle/info-override/main.yaml
__tests__/bundle/info-override/snapshot.js
docs/decorators.md
docs/decorators/info-override.md
packages/core/src/decorators/common/info-override.ts
packages/core/src/decorators/oas2/index.ts
packages/core/src/decorators/oas3/index.ts

This decorator will merge/override additional properties into the info object.
With this decorator you cannot remove some properties from info. Do we need another decorator or some option in this to switch from "merge" to "complete replace" behaviour?
Thoughs?
Added tests.

feat: new decorator info-override

---

__tests__/commands.test.ts
__tests__/split/slash-separator/openapi.yaml
__tests__/split/slash-separator/snapshot.js
packages/cli/src/utils.ts

This updates the `writeYaml` utility function to recursively create directories specified by the file path before creating the file.
This enables the split command to take `--separator=/` and write the split spec as a nested directory structure.
https://github.com/Redocly/redocly-cli/issues/885
- Added an e2e test
- Ran split with `--separator=/` against a valid OpenAPI 3 spec and verified directory structure

fix: support `/` separator in split command

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

v1.0.0-beta.121 release:
- join: add custom output file option(https://github.com/Redocly/redocly-cli/pull/987)
- add an option to include webhooks to operation-4xx-response rule(https://github.com/Redocly/redocly-cli/pull/990)
- fix: ignore case when inferring file extension from codeSample lang prop(https://github.com/Redocly/redocly-cli/pull/991)
- chore: rename features.openapi to theme.openapi for build docs (https://github.com/Redocly/redocly-cli/pull/892)
- chore: rename features.openapi and features.mockServer to theme (https://github.com/Redocly/redocly-cli/pull/995)
- fix: push destination parsing (#890) 
-  feat: new decorator info-override (https://github.com/Redocly/redocly-cli/pull/999)
-  fix: support / separator in split command …

chore: v1.0.0-beta.121

---

packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts

Fix problem with symbols in organization id for the `push` command.
Disallow `@` in destination name;
https://github.com/Redocly/redocly-cli/pull/890

fix: fix destination name validation

---

packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts

- Do not fail the push command when organization is provided via redocly.yaml
- Add more tests for push command

fix: do not fail the push command when organization is provided via redocly.yaml

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release v1.0.0-beta.123
- fix: do not fail the push command when organization is provided via redocly.yaml (https://github.com/Redocly/redocly-cli/pull/1007)
- chore: adjust types for 3.1 (https://github.com/Redocly/redocly-cli/pull/1005)

chore: v1.0.0-beta.123

---

packages/core/src/config/__tests__/__snapshots__/config.test.ts.snap
packages/core/src/config/__tests__/config.test.ts
packages/core/src/config/__tests__/fixtures/ingore-file.ts
packages/core/src/config/config.ts
packages/core/src/format/format.ts

Fix bug if remote schema from added to ignore file.
Fix output for errors if its is url as a pointer
Closes #1013

fix: add handling of absolute url path in ignore-file

---

packages/cli/src/commands/stats.ts

I noticed that `redocly stats` has a funny spacing in its output, where the "Path Items" entry is too close to its emoji
`npm test` works, and the output looks correct when I use my local branch

fix: spacing of path items in stats output

---

packages/cli/src/commands/build-docs/index.ts

Hello.
I wondered why it wasn't outputting to stdout during execution, and when I looked at the source, it was outputting to stderr, so I fixed it.

build-docs command output success message to stdout

---

__tests__/commands.test.ts
__tests__/join/references-in-parameters/bar.yaml
__tests__/join/references-in-parameters/foo.yaml
__tests__/join/references-in-parameters/snapshot.js
packages/cli/src/commands/join.ts
packages/core/src/bundle.ts

Handle $ref in the joining path parameters
Closes: https://github.com/Redocly/redocly-cli/issues/1018

fix: handle $ref in the joining path parameters

---

docs/decorators/info-override.md

I noticed a mismatch between a decorator name and the code example in the docs. The example works when I use it like this.
https://redocly.com/docs/cli/decorators/info-override/

fix: decorator name in a docs example

---

docs/rules.md
docs/rules/custom-rules.md
docs/rules/required-min-length-string-type-property.md
docs/rules/required-string-property-missing-min-length.md

Updated docs for Assertions : 
- Add new property `assertionsProperties` that can be accessible in the `customFn`  instead of the Location. Now location is posted in the assertionsProperties as baseLocation propertie.
New rule: 'required-min-length-string-type-property'.
-  Requires that every property in the API definition with type `string` that are required also to have `minLength`

docs: add docs for reworked assertionFn and new rule

---

packages/core/src/rules/common/required-string-property-missing-min-length.ts
packages/core/src/rules/oas2/index.ts
packages/core/src/rules/oas3/index.ts

fixes: #1050
- [ x] Code is linted
- [ x] All new/updated code is covered with tests

chore: renamed misspelled built-in rule function - `RequiredStringPropertyMissingMunLength`

---

__tests__/bundle/resolve-refs-from-x-attributes/.redocly.yaml
__tests__/bundle/resolve-refs-from-x-attributes/external.yaml
__tests__/bundle/resolve-refs-from-x-attributes/openapi.yaml
__tests__/bundle/resolve-refs-from-x-attributes/plugin.js
__tests__/bundle/resolve-refs-from-x-attributes/resolve-x.decorator.js
__tests__/bundle/resolve-refs-from-x-attributes/snapshot.js
packages/core/src/resolve.ts

Fixed a bug where context.resolve() did not work when applied to nodes belonging to external oas (x-) attributes that contain an array.
Closes: https://github.com/Redocly/redocly-cli/issues/992

fix: resolve external oas attributes with if refs exist in array

---

packages/cli/src/commands/preview-docs/index.ts

Enable whiteLabel options for preview docs by default.

feat: add whiteLabel options for preview by default

---

packages/cli/src/commands/build-docs/utils.ts

related to https://github.com/Redocly/redoc/issues/2290
handle htmlTemplate option for build-docs command.
redocly.yaml
```yaml
theme:
openapi:
htmlTemplate: resources/redocly.html # this setting is ignored
theme:
sidebar:
backgroundColor: '#f2f2f2'
```
resources/redocly.html
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf8" />
<title>Test</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
padding: 0;
margin: 0;
}
</style>
{{{redocHead}}}
{{#unless disableGoogleFont}}<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">{{/unless}}
</head>
<body>
<div>Custom template</div>
{{{redocHTML}}}
</body>
</html>
```

fix: handle htmlTemplate option for build-docs command

---

packages/core/src/config/all.ts

Define default allowedValues in the `all` ruleset for request/response-mime-type rules
Closes: https://github.com/Redocly/redocly-cli/issues/464

fix: define default allowedValues in the all ruleset for mime-type rules

---

__tests__/bundle/no-duplicated-components/.redocly.yaml
__tests__/bundle/no-duplicated-components/Test.yaml
__tests__/bundle/no-duplicated-components/openapi.yaml
__tests__/bundle/no-duplicated-components/paths/path.yaml
__tests__/bundle/no-duplicated-components/snapshot.js
__tests__/bundle/no-self-referenced-components/.redocly.yaml
__tests__/bundle/no-self-referenced-components/openapi.yaml
__tests__/bundle/no-self-referenced-components/parameters/PetId.yaml
__tests__/bundle/no-self-referenced-components/parameters/_index.yaml
__tests__/bundle/no-self-referenced-components/paths/Pet.yaml
__tests__/bundle/no-self-referenced-components/schemas/Pet.yaml
__tests__/bundle/no-self-referenced-components/schemas/_index.yaml
__tests__/bundle/no-self-referenced-components/snapshot.js
__tests__/bundle/no-self-referenced-or-duplicated-components/.redocly.yaml
__tests__/bundle/no-self-referenced-or-duplicated-components/components/schemas.yaml
__tests__/bundle/no-self-referenced-or-duplicated-components/folder/myObject.v2.schema.yaml
__tests__/bundle/no-self-referenced-or-duplicated-components/openapi.yaml
__tests__/bundle/no-self-referenced-or-duplicated-components/snapshot.js
packages/core/src/bundle.ts

We were incorrectly resolving the components pointer. It should get resolved from the root, instead we were resolving from the current node location which breaks if the file is in the folder.
Fixes #658, fixes #290
Tests needed.

fix: duplicated components created when referencing from components

---

packages/cli/src/index.ts

Changes greedy arrays option to false in **yargs**.
This eliminates dependency on position of arguments, e.g. those commands will produce the same result: 
```bash
redocly lint --skip-rule=operation-4xx-response openapi.yaml
redocly lint openapi.yaml --skip-rule=operation-4xx-response
```
To pass an array of values you will have to explicitly point to the option, e.g.: 
```bash 
redocly lint --skip-rule=operation-4xx-response --skip-rule=operation-2xx-response openapi.yaml
```
The change affects **ALL** options behaviour: `--skip-rule`, `--skip-decorator`, `--skip-preprocessor`, `--extends` and `--files`.
Additional motivation is that **yargs** is going to make this behaviour default in next versions ([link](https://github.com/yargs/yargs-parser/blob/main/README.md#greedy-arrays)).
Closes …

fix: avoid different result depending on option arguments position

---

.github/workflows/deploy.yaml
.github/workflows/performance.yaml
.github/workflows/tests.yaml

Added performance benchmarking using `hyperfine`.

chore: add performance benchmark with hyperfine

---

.github/workflows/mlc-link-check.yaml
.mlc.toml
docs/changelog.md
docs/commands/build-docs.md
docs/commands/preview-docs.md
docs/commands/push.md
docs/installation.md
docs/quickstart.md

Ignores relative links since we can only check those from the main
website project.
It's difficult to know when we're breaking links in our docs - this will automatically check on each pull request
Uses MLC (https://github.com/becheran/mlc)
And its GitHub action (https://github.com/marketplace/actions/markup-link-checker-mlc)

Add MLC for link checking

---

packages/core/src/rules/oas3/__tests__/spec-components-invalid-map-name.test.ts
packages/core/src/rules/oas3/spec-components-invalid-map-name.ts

Apply regular expression `^[a-zA-Z0-9\.\-_]+$` only to fixed fields under components
Closes: https://github.com/Redocly/redocly-cli/issues/1104

fix: apply regular expression only to fixed fields under components

---

docs/rules/built-in-rules.md
docs/rules/spec-ref-validation.md
docs/rules/spec-strict-refs.md

Add docs for spec-strict-refs rule
https://github.com/Redocly/redocly-cli/pull/1112

docs: add docs for spec-strict-refs rule

---

docs/file-management.md

The example command uses `bundle` in the documentation about combining OpenAPI files. I guess the correct one should be `join`.

Docs: fix example of command to combine files

---

packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts
packages/cli/src/index.ts

- Add new options `--organization` and `--destination`.
- Mark `maybeApiOrDestination` and `maybeDestination` as deprecated
- Rename `job-id` option and mark `batch-id` as deprecated
Closes: https://github.com/Redocly/redocly-cli/issues/1032

feat: update push command

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Release v1.0.0-beta.129.
This includes the following:
-  #1123
- #1130
- #1132
- #1133
- #1136
- #1137
The related docs changes to be merged: 
- https://github.com/Redocly/redocly-cli/pull/1139

chore: v1.0.0-beta.129

---

packages/cli/src/__tests__/wrapper.test.ts
packages/cli/src/wrapper.ts

Fix problem with `--files` option in `push` command
Related: https://github.com/Redocly/redocly-cli/issues/1148

fix: pass files from '--files' option to config

---

__tests__/lint/oas3.1/openapi.yaml
packages/core/src/rules/common/__tests__/spec.test.ts
packages/core/src/rules/utils.ts

This fixes wrong type validation (broken in **beta.111**).
Since then, we didn't recognise `type: null` being an error:
```yaml
WrongType:
type: null
```
Whilst the `null` should be a string:
```yaml
CorrectType:
type: "null"
```
The original MR: https://github.com/Redocly/redocly-cli/pull/891

fix: correctly validate schema `type: null`

---

packages/cli/src/__tests__/fetch-with-timeout.test.ts
packages/cli/src/fetch-with-timeout.ts
packages/cli/src/update-version-notifier.ts
packages/cli/src/utils.ts

Adding fetch request timeout to prevent hanging the tool when executing commands. 
https://github.com/Redocly/redocly-cli/issues/1146

fix: add timeout for unnecessary calls

---

package-lock.json
packages/cli/package.json

Move "redoc-related" packages into peer dependencies in order to avoid having different versions
Releated: https://github.com/Redocly/redocly-cli/issues/1073

fix: resolve issue with broken styles in build-docs command

---

packages/cli/src/fetch-with-timeout.ts

Using `global.AbortController` to prevent failing when there's no AbortController in NodeJS.
Hotfix for https://github.com/Redocly/redocly-cli/pull/1150

chore: fix failing on node 14-

---

docs/installation.md

Update docker installation guide, add option to pull image from GitHub packages.

docs: update docker installation guide

---

docs/guides/migrate-from-spectral.md

Add a migration guide for users migrating from Spectral. Includes a best-effort list of rules, to help with the translation process. This probably will need lots of updates as we get feedback from migrating users.

Docs for migrating from Spectral to Redocly CLI

---

.changeset/great-impalas-explain.md
packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
packages/core/src/config/all.ts
packages/core/src/config/minimal.ts
packages/core/src/config/recommended.ts

We expose default severity levels for `assertions` in our predefined rulesets what doesn't make too much sense as we don't have any default assertions. And once someone adds an assertion to their **redocly.yaml**, we use `error` as a default severity regardless of the defined in the ruleset. 
Also it contradicts with our current types as we expect the `assertions` field to be of type `Assertion[]`: https://github.com/Redocly/redocly-cli/blob/2e02eda23ba173633db8820fd6d38d65967856b9/packages/core/src/rules/common/assertions/index.ts#L28

fix: remove assertions severity from default rulesets

---

.github/CONTRIBUTING.md
.github/workflows/release.yaml
scripts/archive-and-upload-bundle.js

Fixes release pipeline for Dockerhub + Github packages (was publishing version `main` instead of the actual version), and S3 (was publishing v1.0 instead of the actual one).

chore: fix release pipeline

---

.changeset/hot-bulldogs-grow.md
packages/core/src/rules/oas2/__tests__/remove-unused-components.test.ts
packages/core/src/rules/oas2/remove-unused-components.ts
packages/core/src/rules/oas3/__tests__/remove-unused-components.test.ts
packages/core/src/rules/oas3/remove-unused-components.ts

…a child object. fixes #1207
Core problem is described in #1207 
Fixes #1207
I added a test case for this. I'm not 100% sure that this is the best location for this test but it seemed natural to me.
I've also tested this on a non-trivial OpenAPI document that has dozens of these cases.

fix: do not remove components which are only used via a reference to a child object

---

.changeset/hot-pens-fetch.md
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/commands/join.ts

Currently, all features except "join" support OAS3.1.
Closes https://github.com/Redocly/redocly-cli/issues/1021
Added a unit test.

Support OAS3.1 for joining (fixes #1021) 

---

.github/pull_request_template.md
.github/workflows/performance.yaml
.github/workflows/release.yaml
package-lock.json
package.json
scripts/post-changeset.js

Makes release message in Slack useful:
```
:bookmark: New @redocly/cli release 1.1.0
*Minor Changes*
•   Testing.
*Patch Changes*
•   Testing...
:bookmark: New @redocly/openapi-core release 1.1.0
*Patch Changes*
•   Testing...
```
Also, it attempts to fix failure on the performance check due to lack of permissions (when running from a fork) - added a check if the repository that triggered the event is the same as the base one.

chore: fix Slack release message

---

package-lock.json

Rollbacking the wrong `openapi-core` version in package-lock.json.

chore: rollback the wrong openapi-core version in package-lock

---

.github/workflows/performance.yaml

Fix identifying a fork PR
Notice the [performance pipeline](https://github.com/Redocly/redocly-cli/actions/runs/5866521606/job/15905481387?pr=1231) not failing.

chore: do not comment on a PR created from a fork

---

.github/workflows/smoke.yaml
package-lock.json
packages/cli/package.json
packages/cli/src/__tests__/commands/build-docs.test.ts
packages/cli/src/assert-node-version.ts
packages/cli/src/commands/preview-docs/preview-server/preview-server.ts
packages/cli/src/utils.ts
packages/core/package.json

- Set minimal `Node.js` version to 14
- Remove unsupported `assert-node-version` and `glob-promise` dependencies
- Replace `portfinder` with `get-port-please` package
https://github.com/orgs/Redocly/projects/12/views/5?pane=issue&itemId=35308489

chore: replace stale dependencies

---

.changeset/forty-onions-deliver.md
docs/rules/tags-alphabetical.md
packages/core/src/rules/common/__tests__/tags-alphabetical.test.ts
packages/core/src/rules/common/tags-alphabetical.ts

For human perception, case doesn't really make a huge difference, especially when trying to find an item on the list. We used to have a custom assertion to do the same thing, but with an `ignoreCase` option to achieve the goal (see referenced PR).
https://github.com/Rebilly/api-definitions/pull/1590
Test cases were added to cover the option.

Add `ignoreCase` for `tags-alphabetical` rule

---

.github/workflows/release.yaml

Post-release smokes are somewhat flaky by design. It's ok that they might fail sometimes. Anyways, we need to send a release message. This MR allows it to work that way even if some post-release smokes fail. 
During the next release.

chore: send release message even if post release smokes fail

---

.changeset/dull-ducks-beam.md
__tests__/commands.test.ts
__tests__/join/multi-references-to-one-file/bar.yaml
__tests__/join/multi-references-to-one-file/foo.yaml
__tests__/join/multi-references-to-one-file/nested/FooObject.yaml
__tests__/join/multi-references-to-one-file/nested/Response.yaml
__tests__/join/multi-references-to-one-file/snapshot.js
packages/cli/src/commands/join.ts
packages/core/src/resolve.ts

Fixed an issue with nested refs in the join command
The problem occurs when two files have a reference to one file, and this file contains another references
When we resolve multiple documents with one `BaseResolver`, we share a common cache. When we try to resolve an already cached document, we get a reference to the node in the cache
The bundle visitor mutates the node, which can be a reference to the cache . Therefore, for the next document, the values in the cache will have already been changed and the node may be invalid for this document, since it will contain a reference to the component section, not to the file.
Solution: Use a separate `BaseResolver` (with its own cache) for each file during  `bundle`
https://github.com/Redocly/redocly-cli/issues/1268

fix: use separate resolvers for each file in join

---

.changeset/slow-lemons-accept.md
packages/core/src/types/asyncapi.ts
packages/core/src/types/oas3_1.ts

Per JSON Schema 2019-09+ spec. this annotation keyword can be any valid JSON Schema schema. e.g. `boolean` or `schema` https://json-schema.org/draft/2019-09/json-schema-core#unevaluatedItems
partially fixes #1233
The type definition for `unevaulatedItems` was incorrect per the JSON Schema 2019-09 specification
https://json-schema.org/draft/2019-09/json-schema-core#unevaluatedItems
- [ x] Code is linted

fix(types): update unevaluatedItems type defintion

---

docs/rules/configurable-rules.md

`notPattern` rule defined an invalid type of `property: The summary`
- [x ] Code is linted

fix(docs): update example

---

.changeset/plenty-mugs-suffer.md
__tests__/commands.test.ts
__tests__/join/json-and-yaml-input/bar.yaml
__tests__/join/json-and-yaml-input/foo.json
__tests__/join/json-and-yaml-input/json-output.snapshot.js
__tests__/join/json-and-yaml-input/yaml-output.snapshot.js
__tests__/join/multi-references-to-one-file/openapi.yaml
__tests__/join/yaml-input-and-json-output/bar.yaml
__tests__/join/yaml-input-and-json-output/foo.yaml
__tests__/join/yaml-input-and-json-output/snapshot.js
__tests__/split/openapi-json-file/openapi.json
__tests__/split/openapi-json-file/snapshot.js
docs/commands/join.md
packages/cli/src/__mocks__/@redocly/openapi-core.ts
packages/cli/src/__mocks__/utils.ts
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/__tests__/utils.test.ts
packages/cli/src/commands/join.ts
packages/cli/src/commands/split/__tests__/index.test.ts
packages/cli/src/commands/split/index.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts

Extend `split` and `join` commands to optionally produce JSON output.
Determine the output format by the extension of the input file, if the extension is not supported use `yaml`
Supported file extensions: `json`, `yaml`, `yml`
Determine the output format by the extension of the file from `output` option, if output option is not provided use extension of first entry point, if extension not supported use `yaml`.
Supported file extensions: `json`, `yaml`, `yml`
Related: https://github.com/Redocly/redocly-cli/issues/1205

feat: extend split and join commands to produce JSON output

---

.changeset/strange-insects-jog.md
packages/cli/src/commands/preview-docs/preview-server/hot.js
packages/cli/src/commands/preview-docs/preview-server/preview-server.ts
packages/cli/src/commands/preview-docs/preview-server/server.ts

Today the WS server used for hot reloading is initialized without specifying a host. But in the `hot.js` file, `127.0.0.1` is hardcoded as the host it should connect to. This breaks in some cases, such as when the websocket server binds to ipv6, and therefore isn't available on `127.0.0.1`.
This PR changes it so that the host provided via `--host` or `-h` is passed on to the WS server as well, not only to the http server. It also adds this host as a global variable, alongside the `wsPort` variable, so that `hot.js` can pick up the correct host when connecting to the websocket; instead of the hardcoded host today.
No tests seem to exist for the preview-server functionality and I have not added any. Instead I have tested manually with a variety of commonly used hosts (`::`, `0.0.0.0`, …

fix: use same host for websocket server as for http server when previewing locally

---

.changeset/short-poets-sleep.md
packages/core/src/__tests__/lint.test.ts
packages/core/src/types/oas3_1.ts

OpenAPI 3.1.x defaults to JSON Schema draft 2020-12 and the value of property names defined in `properties` was updated since OpenAPI 3.0.x and JSON Schema draft-04. 
In the new JSON Schema specification, each property value within a `properties` schema accepts a `boolean` or `object` schema.
fixes #1296 
https://json-schema.org/draft/2020-12/json-schema-core#section-10.3.2.1

OAS3_1 types `SchemaProperties` updated per JSON Schema draft 2020-12

---

README.md

Updating README to talk about API Style Guides, to be consistent with how other tools talk about it. 
If this approach is good we can update the rest of the docs to follow along the same lines, downplaying "API Standards" (the word standard is already massively overloaded in the world of APIs) and hype up Rulesets are a technical implementation of an API Style Guide (Rulesets focused on helping you design and build better APIs) or OpenAPI Style Guides (Rulesets helping you write better OpenAPI, but doesn't really tell you how to write the API itself.)

Lets talk about API Style Guides

---

.changeset/twelve-kids-tan.md
packages/core/src/env.ts

Bun exposes self by default and the validation from https://github.com/Redocly/redocly-cli/blob/eadf29f6a89f49136ce097e665f6b92a8c4ecec1/packages/core/src/env.ts#L4 wrongly assumes isBrowser is true

fix: improve browser detection when running with Bun

---

README.md

fix contributions link
don't point to .github folder

Contributions link was 404

---

.changeset/silver-singers-glow.md
docs/rules/array-parameter-serialization.md
packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
packages/core/src/config/all.ts
packages/core/src/config/minimal.ts
packages/core/src/config/recommended-strict.ts
packages/core/src/config/recommended.ts
packages/core/src/rules/oas3/__tests__/array-parameter-serialization.test.ts
packages/core/src/rules/oas3/array-parameter-serialization.ts
packages/core/src/rules/oas3/index.ts
packages/core/src/types/redocly-yaml.ts
packages/core/src/typings/openapi.ts

Create new rule `array-parameter-serialization` rule to enforce array parameters format.
This Rule enforces to define  fields `explode` and `style` for parameter if param's schema type is `array` or has `items` or `preffixItems`
https://github.com/Redocly/redocly-cli/issues/1317

feat: create new rule to enforce array parameters format

---

docs/rules/configurable-rules.md

Adding a signpost to the cookbook to signpost to more configurable rules examples.
(this minor change is also to test if we can publish docs)

docs: Add a cookbook mention to the configurable rules page

---

.changeset/bright-steaks-walk.md
package.json

Adjusting the `npm run clean` command to clear the dist/ folder as well.
Removing a redundant changeset.

chore: adjust the clean command and remove redundant changeset

---

docs/guides/lint-asyncapi.md

Replace old  link to async api specification v2.6.0

chore: update link to async api specification

---

docs/custom-plugins/custom-rules.md

We got a feedback item about an incorrectly named import in a code sample. This fixes it.

docs: Minor fix to code sample from website feedback

---

.changeset/new-books-cross.md
docs/commands/join.md
packages/cli/src/__mocks__/utils.ts
packages/cli/src/commands/bundle.ts
packages/cli/src/commands/join.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts

Add deprecate warning for the `--lint` option in the `join` command.
Related: https://github.com/Redocly/redocly-cli/issues/1250

chore: deprecate lint option in the join command

---

docs/decorators/filter-in.md
docs/decorators/filter-out.md

Our filter-in and filter-out decorators have had examples "coming soon" for ages. This PR adds some examples!
- https://redocly.com/docs/cli/decorators/filter-in/
- https://redocly.com/docs/cli/decorators/filter-out/
Created working examples locally before adding to the docs.

Docs: Add examples for the filter decorators

---

docs/configuration/index.md

Added docs for $refs in the config file: https://github.com/Redocly/redocly-cli/pull/1345.
Merge this alongside [the release](https://github.com/Redocly/redocly-cli/pull/1361).

docs: explain using refs in a config file

---

docs/guides/migrate-from-swagger-cli.md

Fixed typo in the migration guide

docs: fix typo in the migration guide

---

docs/rules/configurable-rules.md

Fixes #649 by adding a clarifying note that markdown fields may have trailing newlines.

docs: Add a note about expected newlines in multiline markdown fields

---

__tests__/bundle/bundle-lint-format/emptyFormatValue-snapshot.js
__tests__/lint-config/invalid-lint-config-severity/snapshot.js
packages/cli/src/index.ts

Fixes #1237 (or tries to) by using more consistent language and expanding descriptions show in the output of `redocly --help`.

feat: Improve CLI help output

---

docs/rules/configurable-rules.md

The description was not quite correct. Fixed based on #1351 (kudos to @jeremyfiel!).

docs: correct description of multiline patterns usage based on #1353

---

.github/workflows/docs-tests.yaml

Vale has a new release (yay!) but it came with some directory structure changes and these are causing the build to fail. This pull request pins to a working version and I'll follow up with another one to handle the v3 update.

chore: pin Vale in GitHub action to last v2 vale version until we update to v3

---

docs/guides/index.md
docs/guides/lint-and-bundle.md
docs/sidebars.yaml

Linting, and then only bundling if the lint was successful, is a good practice pattern. This guide explains how it works, and shows how to combine the two commands.
Related to (but does not fix) #1250

docs: add a guide for linting and bundling as two separate but chained commands

---

package-lock.json
package.json
packages/core/package.json

Currently, `@types/node` is a dependency in the `@redocly/openapi-core` package. As these are only TypeScript types, they are not needed in production and can be moved to a dev dependency.
Also, there is already a `@types/node@17.0.31` in the root package. My question would be whether the dependency there should be sufficient and whether the dependency should be changed to a more up-to-date version.

chore: move TypeScript type dependencies to dev dependencies

---

.changeset/loud-eagles-decide.md
Dockerfile

Added the ability to use git operations in the docker image to use it in CICD runners.

feat: added the ability to use git operations in the docker image

---

docs/rules/configurable-rules.md

Markdownlint started complaining about a table in the configurable rule documentation. This pull request fixes the reported problems (the rendering was and is fine).

docs: Fix an incorrectly-formatted table in the custom function docs for configurable rules

---

.changeset/pink-waves-press.md
__tests__/commands.test.ts
__tests__/miscellaneous/resolve-refs-in-preprocessors/snapshot.js
__tests__/stats/stats-json/museum.yaml
__tests__/stats/stats-json/snapshot.js
__tests__/stats/stats-markdown/museum.yaml
__tests__/stats/stats-markdown/snapshot.js
__tests__/stats/stats-stylish/museum.yaml
__tests__/stats/stats-stylish/snapshot.js
packages/cli/src/commands/stats.ts
packages/cli/src/index.ts
resources/museum.yaml

I was answering a question about JSON format output containing not-JSON elements, and I also noticed #976 requesting markdown format output that could be used in other contexts, such as [GitHub Job Sumaries](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).
So this pull request removes the output about which file is being `stat`-ed from being displayed by default - the stylish format keeps it as that one is human readable. The execution time output is also removed, this isn't used in all commands and breaks the other file formats such as JSON.
The pull request also adds a `--format=markdown` option to the `stats` command, to produce a markdown output. The original request was for the GitHub Job Summaries, but the format is …

feat: add markdown output format to stats command

---

.changeset/thin-badgers-worry.md
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts

Fixed an issue with the `push` command, when `destination` option does not work without specifying it in `redocly.yaml`.

fix: resolve an issue with options in the push command

---

packages/cli/src/utils/update-version-notifier.ts

We did a new release yesterday and I noticed that when I get the release banner, I also get slightly indented output from whichever command I was using.

fix: extra whitespace after update notifier

---

packages/cli/src/cms/commands/__tests__/push-status.test.ts
packages/cli/src/cms/commands/push-status.ts
packages/cli/src/utils/js-utils.ts

Fix the wording and eliminate uppercase for messages in both the `push-status` and `push` commands.

fix: update `push-status` messages

---

docs/sidebars.yaml

Adding link to `no-required-schema-properties-undefined` custom rule in sidebar.
n/a
n/a
n/a
n/a

docs: link no-required-schema-properties-undefined rule in sidebar

---

docs/sidebars.yaml

Fix wrong file extension for sidebar.yaml docs.
n/a
n/a
n/a
No

docs: fix wrong file extension for sidebar.yaml docs

---

.github/workflows/require-changeset.yaml
packages/cli/src/index.ts

We do not need to check for a changeset in the release branch. This PR skips the check when a PR was created from `changeset-release/main`.

chore: do not run the reqire changeset action on release branch

---

.changeset/spotty-pets-doubt.md
__tests__/commands.test.ts
__tests__/join/prefix-components-with-info-prop/bar.yaml
__tests__/join/prefix-components-with-info-prop/snapshot.js
__tests__/split/discriminator-in-json/openapi.json
__tests__/split/discriminator-in-json/snapshot.js
packages/cli/src/__mocks__/@redocly/openapi-core.ts
packages/cli/src/__mocks__/documents.ts
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/commands/join.ts
packages/cli/src/commands/split/index.ts
packages/cli/src/commands/split/types.ts
packages/cli/src/utils/js-utils.ts

Since 1.9.0 `join` fails when used with the --prefix-components-with-info-prop option and a schema contains `null` value.
This PR resolves the issue by moving the crawl [visitor](https://github.com/Redocly/redocly-cli/pull/1444/files#diff-e52f3b6820e3de0cd0ec76de555265a5139350fdfa3cd210402edeaa9fdd56eeR151) out of the loop. 
Also, did a small refactoring of `split` command (reusing shared things with `join`, types correction).
Fixes https://github.com/Redocly/redocly-cli/issues/1440

fix: join command failing on null values with --prefix-components-with-info-prop option

---

.changeset/slimy-planes-deliver.md
packages/core/src/__tests__/ref-utils.test.ts
packages/core/src/ref-utils.ts

Since the last release, $refs has been resolved incorrectly when a file names contain the hash character. This was due to splitting URIs by '#' instead of '#/'. 
This PR reverts this change while still allowing URIs to end with '#'.
Fixes https://github.com/Redocly/redocly-cli/issues/1441
Corresponding docs: https://json-schema.org/draft/2020-12/draft-bhutton-json-schema-00#idExamples

fix: parse $refs containing the hash symbol correctly

---

.github/workflows/docs-tests.yaml

We created a changelog entry with weird formatting, but the tools didn't catch it on this repo, only on the marketing repo. Try to align the tools to match.
https://github.com/Redocly/marketing-site-portal/actions/runs/7891589237/job/21536235829?pr=1190

docs: try updating the markdownlint tool version

---

CONTRIBUTING.md

Someone can copy and paste the command from our example and it won't work. 
Kudos to @lesyk-lesyk for spotting this.

chore: use real opanapi file in an example for clarity

---

.changeset/sixty-jars-listen.md

Bump cli and core version to resolve problem caused by https://github.com/Redocly/redocly-cli/pull/1458

chore: bump version

---

.changeset/wild-pets-report.md
docs/installation.md
package-lock.json
packages/cli/src/__mocks__/@redocly/openapi-core.ts
packages/cli/src/cms/api/__tests__/api.client.test.ts
packages/cli/src/cms/api/api-client.ts
packages/cli/src/commands/push.ts
packages/cli/src/utils/fetch-with-timeout.ts
packages/core/package.json
packages/core/src/bundle.ts
packages/core/src/config/config.ts
packages/core/src/config/load.ts
packages/core/src/decorators/common/registry-dependencies.ts
packages/core/src/index.ts
packages/core/src/redocly/__tests__/domains.test.ts
packages/core/src/redocly/__tests__/redocly-client.test.ts
packages/core/src/redocly/domains.ts
packages/core/src/redocly/index.ts
packages/core/src/redocly/registry-api.ts
packages/core/src/utils.ts

Adding https-proxy-agent package to fix issues with requests when using CLI behind proxy. Create better mechanism for handling `env.REDOCLY_DOMAIN` usage in few modules. 
Now if you need to run the CLI tool behind a proxy, you can use the HTTP_PROXY and HTTPS_PROXY environment variables to configure the proxy settings.
`https-proxy-agent` package was used for `node-fetch` requests. Now we pass agent for every `fetchWithTimeout` request, as well as other regular `fetch` request.
This is a rollback of a rollback https://github.com/Redocly/redocly-cli/pull/1458 
After encountering problems with some of the packages from `https-proxy-agent` dependencies, we had to ignore this package for browser environment, by modyfing `packages/core/package.json` like so:
```
"browser": { …
```

fix: fix issues with https-agent-proxy for cli and openapi-core packages

---

.changeset/cuddly-cheetahs-teach.md
packages/cli/src/commands/preview-project/index.ts

To execute an `npx` command using `spawn` on Windows, the provided executable name has to be `npx.cmd` instead of `npx`. Because this wasn't handled, the npx command was crashing on Windows with an `ENOENT` error.
Error on Windows

fix: fix preview command on windows

---

.changeset/moody-parents-fry.md
packages/core/src/env.ts

`openapi-core` fails when running inside a worker because it doesn't recognise it's not a `node` environment` (i.e. inside a language server). Added a check for that case. 
Kudos to @jacobator

fix: prevent failing in worker

---

.changeset/old-cats-shave.md
packages/core/src/types/redocly-yaml.ts

Allow additional properties in the `theme.openapi` config definition

fix: allow additional properties in theme.openapi

---

docs/rules/configurable-rules.md

I don't know how long the site has been down or when it might be back up, but for now it is breaking our preview builds on the Marketing site so I am removing these links.
I ran mlc locally and it has fixed the errors.

Removes two links to the yaml spec as the site is down

---

docs/commands/join.md

Removing tabs tags from the join page. They were partially removed already and causing tag issues in downstream builds.
Ran the documentation preview while making the changes.

docs: remove tabs from join command page

---

.github/ISSUE_TEMPLATE/gsod-project-ideas.md
docs/gsod/2024/proposal.md

We want to participate in Google Season of Docs 2024 and to do so we need a public proposal page that can be commented on and discussed within the community. Since this repo is public it is the ideal location, particularly since one of the projects will be to enhance the guides doc within this project.
This PR also includes a new issue template specific to gsod discussion so that it won't get easily mixed up with the bug or feature requests for the project itself.
Closes [this issue](https://github.com/Redocly/marketing-site-portal/issues/1212)
I built it locally in the marketing site, so the formatting should work once it is pulled into the marketing site.

docs: adds gsod 2024 folder and proposal page

---

docs/gsod/2024/proposal.md

There was a space addd to the closing Markdoc bracket that kept the final budget table from showing up on the gsod proposal page. This PR is to fix that spacing issue.

docs: fixes spacing issue that cut budget table out of gsod proposal doc

---

.changeset/metal-countries-complain.md
packages/core/src/types/redocly-yaml.ts

Fixes failures on the `metadata-schema` rule.

fix: add type tree for metadata-schema rule

---

docs/configuration/index.md
docs/configuration/reference/apis.md
docs/configuration/reference/decorators.md
docs/configuration/reference/extends.md
docs/configuration/reference/plugins.md
docs/configuration/reference/preprocessors.md
docs/configuration/reference/resolve.md
docs/configuration/reference/rules.md
docs/sidebars.yaml

We have some config options that are in use in the CLI, but the rest of the config docs are still private for the new products. Create matching-format pages for the options that belong here so we can link to them.

docs: add cli config reference

---

.changeset/funny-hornets-agree.md
packages/core/src/rules/oas3/__tests__/no-invalid-media-type-examples.test.ts
packages/core/src/rules/oas3/no-invalid-media-type-examples.ts

Currently, when an example object has `externalValue` property [`no-invalid-media-type-examples`](https://redocly.com/docs/cli/rules/no-invalid-media-type-examples/) lint rule fails as it is validating the _example_ object (the parent object) against the schema definition.
I could assume there are couple of ways to handle this case. However, as there is already another lint rule ([`no-example-value-and-externalValue`](https://redocly.com/docs/cli/rules/no-example-value-and-externalValue/)), which is kind of related to this one, and its default severity level causes either one of `value`, or `externalValue` properties to exist for a specific example object, I decided to go with the simple exclusion condition, which basically deactivates the validation for example objects that has …

Ignore validating example with externalValue against schema

---

.changeset/many-steaks-hope.md
packages/core/src/bundle.ts
packages/core/src/config/__tests__/config-resolvers.test.ts
packages/core/src/config/__tests__/fixtures/load-external.yaml
packages/core/src/config/__tests__/load.test.ts
packages/core/src/config/config-resolvers.ts
packages/core/src/config/load.ts

Currently, when resolving the config, the external refs' resolver gets re-declared inside the `resolveConfig` function. That makes caching some external resources (particularly those from the `extends` config section) impossible. Also, those disconnected resolvers make it impossible to substitute the fs provider (it's useful when working in a browser environment).
This PR eliminates the discrepancy and allows using one `externalRefResolver` throughout the entire `loadConfig` function.

fix: resolve config extensions using only one resolver

---

CONTRIBUTING.md

fixed the incorrect command to preview local docs changes in contributing.md
https://github.com/Redocly/redocly-cli/issues/1532
vscode preview of markdown file `contributing.md`
ran `vale \docs`
checked with `markdownlint` vscode extension

fix: correct contribute documentation preview locally (#1532)

---

.changeset/young-apes-sell.md
packages/core/src/config/__tests__/load.test.ts
packages/core/src/config/load.ts
packages/core/src/utils.ts

This PR addresses two issues:
- prevents the `loadConfig` function from failing in browser environment
- removes auth requests to the registry api when loading a config file (which cause perf issues)
Partially related to: 
- https://github.com/Redocly/redocly/pull/7883
- https://github.com/Redocly/redocly/issues/8381

fix: prevent loadConfig from failing in browser env and do not sent auth requests

---

.changeset/hot-vans-smile.md
packages/core/src/config/load.ts

Return a default fallbeck if there is no config file for the provided path.

fix: check if the config file exists

---

packages/core/src/config/load.ts
packages/core/src/env.ts
packages/core/src/format/format.ts
packages/core/src/resolve.ts

- Added checks for browser environment when using Node.js features in openapi-core.
- Removed needless [try...catch](https://github.com/Redocly/redocly-cli/pull/1565/files#diff-91233afeb25fea2c651ad22452d823830a0c6e8378deba81a1109b57cdae3fb6L149) block.

chore: add checks for browser env

---

.changeset/strong-crews-change.md
packages/core/src/rules/common/__tests__/no-invalid-parameter-examples.test.ts
packages/core/src/rules/common/__tests__/no-invalid-schema-examples.test.ts
packages/core/src/rules/common/no-invalid-parameter-examples.ts
packages/core/src/rules/common/no-invalid-schema-examples.ts
packages/core/src/rules/oas3/__tests__/no-invalid-media-type-examples.test.ts
packages/core/src/rules/oas3/no-invalid-media-type-examples.ts

Fixed a small issue in `no-invalid-media-type-examples`, `no-invalid-parameter-examples`, and `no-invalid-schema-examples` rules which allowed to pass falsy examples for any schema.

fix: falsy values in no-invalid-media-type-examples, no-invalid-parameter-examples, and no-invalid-schema-examples rules

---

.changeset/shy-cherries-tie.md
__tests__/miscellaneous/resolve-refs-in-preprocessors/snapshot.js
__tests__/stats/stats-json/snapshot.js
__tests__/stats/stats-markdown/snapshot.js
__tests__/stats/stats-stylish/snapshot.js
docs/commands/stats.md
packages/cli/src/commands/stats.ts

The ➡️ should be the same width as other emojis normally though it shows differently in GitHub's code viewer (`➡️`). Currently, the additional space makes the `stats` subcommand print such outputs, which is weird
The PR fixes it by removing the space.

chore: replace ➡️ with 🔀 to align the words

---

.github/workflows/performance.yaml

Reverting changes in the historical benchmark pipeline introduced by a mistake [here](https://github.com/Redocly/redocly-cli/pull/1593/files#diff-6430b1987c0968143b0c52c4307f47c660827da3bc20f60862f40423b96267fdR67), which cause [this failure](https://github.com/Redocly/redocly-cli/actions/runs/9745432780/job/26893357203?pr=1596). 
It's a separate benchmark test command, not the root level one.

chore: fix the historical benchmark pipeline

---

docs/commands/preview.md

We received some feedback that it isn't clear enough that the preview command is only for early access users. This pull request upgrades the admonition level in an attempt to make it more likely it will be seen/read.

docs: try to make it clearer that preview is for next-gen products

---

.mlc.toml

We have a link checker, but if a 3rd party site is down then we see a build failure when in fact it's not a fault on our side. This pull request adjusts the link checking to be local-only in the CI pipeline that is used on every pull request.
This change brings the checks in line with the other docs sites.

chore: change link checker config to internal links only

---

docs/commands/build-docs.md
docs/commands/bundle.md
docs/commands/check-config.md
docs/commands/completion.md
docs/commands/index.md
docs/commands/join.md
docs/commands/lint.md
docs/commands/login.md
docs/commands/logout.md
docs/commands/preview-docs.md
docs/commands/preview.md
docs/commands/push.md
docs/commands/split.md
docs/commands/stats.md

Updated commands documentation per issue 1429 and also made minor changes for correction and consistency.
https://github.com/Redocly/redocly-cli/issues/1429
Ran redocly preview for local development.
Ran spelling check.
Ran vale.
Ran mlc.
Ran markdownlint.

docs: update commands documentation (issue 1429) and minor corrections

---

packages/core/src/types/arazzo.ts

Arazzo parameter schema update: added `body` to the allowed parameter `in` value.

fix: arazzo parameter schema update

---

.changeset/hungry-files-scream.md
packages/core/src/types/oas3.ts

related #707
This is a JSON Schema keyword but **IS NOT** supported by OpenAPI 3.0.x.  This type was incorrectly added to the Schema object typings. 
related https://github.com/OAI/OpenAPI-Specification/pull/741#issuecomment-235959201

Remove unsupported keyword OAS 3.0.x typing - `additionalItems`

---

packages/cli/src/commands/join.ts
packages/cli/src/commands/split/index.ts
packages/core/src/bundle.ts
packages/core/src/utils.ts

chore: use dequal instead of lodash.isequal

---

.changeset/forty-planes-dream.md
__tests__/bundle/oas3_1-pattern-porperties/object.yaml
__tests__/bundle/oas3_1-pattern-porperties/redocly.yaml
__tests__/bundle/oas3_1-pattern-porperties/snapshot.js
__tests__/bundle/oas3_1-pattern-porperties/test.yaml
packages/core/src/types/oas3_1.ts

Added correct typing for JSON Schema `patternProperties`.
Fixes #792

fix: add correct typing for patternProperties

---

.changeset/five-cougars-arrive.md
packages/core/src/rules/common/__tests__/spec.test.ts
packages/core/src/types/oas3_1.ts

When validating an OpenAPI 3.1 spec that utilizes `dependentSchemas`, `redocly-cli` emits an error:
```json
{
"ruleId": "spec",
"severity": "error",
"message": "Expected type `SchemaList` (array) but got `object`",
"suggest": [],
"location": [
{
"source": {
"ref": "https://raw.githubusercontent.com/json-api/json-api/a2034598b22daf77322b9123c707165ef3ead3ea/schemas/1.0/schema.json"
},
"pointer": "#/dependentSchemas",
"reportOnKey": false
}
]
}
```
which led me to discover that `dependentSchemas` was configured to be an array, but is in fact [a map](https://json-schema.org/draft/2020-12/json-schema-core#section-10.2.2.4).
https://github.com/Redocly/redocly-cli/blob/368c34fc5faa8e9e920a1c003b19350cee47224e/packages/core/src/types/oas3_1.ts#L136
The line in question dates to the initial …

Treat `dependentSchemas` as a map not array.

---

docs/usage-data.md
packages/cli/src/__tests__/commands/build-docs.test.ts
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/__tests__/commands/push-region.test.ts
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/__tests__/wrapper.test.ts
packages/cli/src/cms/commands/__tests__/push-status.test.ts
packages/cli/src/cms/commands/__tests__/push.test.ts
packages/cli/src/cms/commands/push-status.ts
packages/cli/src/cms/commands/push.ts
packages/cli/src/commands/build-docs/index.ts
packages/cli/src/commands/bundle.ts
packages/cli/src/commands/join.ts
packages/cli/src/commands/lint.ts
packages/cli/src/commands/login.ts
packages/cli/src/commands/preview-docs/index.ts
packages/cli/src/commands/preview-project/index.ts
packages/cli/src/commands/push.ts
packages/cli/src/commands/split/__tests__/index.test.ts
packages/cli/src/commands/split/index.ts
packages/cli/src/commands/stats.ts
packages/cli/src/utils/miscellaneous.ts
packages/cli/src/wrapper.ts
packages/core/src/bundle.ts
packages/core/src/lint.ts
packages/core/src/oas-types.ts
packages/core/src/utils.ts

Aggregate data regarding API types and versions usage.
~Important: it's better to wait until https://github.com/Redocly/redocly-cli/pull/1493 is merged. Otherwise could run into multiple merge conflicts.~
Resolves https://github.com/Redocly/redocly-cli/issues/1297

chore: aggregate data regarding API types and versions usage

---

.changeset/short-onions-live.md
__tests__/miscellaneous/resolve-refs-in-preprocessors/snapshot.js
__tests__/stats/stats-json/snapshot.js
__tests__/stats/stats-markdown/snapshot.js
__tests__/stats/stats-stylish/snapshot.js
packages/cli/src/commands/stats.ts
packages/cli/src/wrapper.ts
packages/core/src/rules/other/stats.ts
packages/core/src/typings/common.ts

stats command was crashing for GitHub API (tags was undefined).
Also added support for webhooks in stats.

fix: add webhooks to stats and fix crash for webhooks tags

---

docs/custom-plugins/custom-decorators.md

We have lots of custom decorators in the cookbook now, so add a link to the cookbook from the decorators page.

docs: Link to the cookbook from the custom decorators page

---

.changeset/tough-gifts-tell.md

Fix Vale error on a release PR: https://github.com/Redocly/redocly-cli/pull/1664

chore: fix vale error

---

docs/commands/push-status.md
docs/commands/push.md

All of the commands use 3-column tables except for the Reunite push and push-status commands.
Move the Reunite tab before the Workflows tab.
n/a
n/a

docs: move to 3-column tables for push and push-status commands

---

.changeset/curvy-rivers-itch.md
packages/core/src/config/config-resolvers.ts

The `resolveConfig` function tried to use the `existsSync` function from the `fs` module in a browser which resulted in an error being thrown.

fix: resolve config in browser throws an error

---

docs/installation.md

We received user feedback that the `yarn global` command is not supported in newer versions of yarn, so drop these instructions.
(internal feedback link) https://app.cloud.redocly.com/org/redocly/project/marketing-site/feedback/fb_01j5wyxcs83a19tebkxdn8gd1q
Affected page: https://redocly.com/docs/cli/installation

docs: remove outdated yarn install instructions

---

docs/guides/lint-asyncapi.md
docs/guides/migrate-from-swagger-cli.md

Spotted a stray `::: info` in one of our guides, so I updated to the new admonition format. Grep also found another one that was in comments, removed that one.
https://redocly.com/docs/cli/guides/lint-asyncapi#configurable-rule-example

docs: Fix an outdated admonition format

---

.changeset/strange-gifts-clap.md
packages/core/src/config/config-resolvers.ts

Error with use plugin:
```node
Something went wrong when processing :                                                                                  
- Failed to load plugin "plugins/myapi.js": Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 's:'
```
More info: https://github.com/Redocly/redocly-cli/issues/1673
Tested in Windows
No tested in Linux.
Please, test in Linux.

fix resolve path for import plugin, after upgrade 1.20.0

---

.changeset/wicked-birds-jam.md
packages/cli/src/commands/eject.ts
packages/cli/src/commands/preview-project/index.ts
packages/cli/src/index.ts

Added the ability to run the `eject` command without specifying components, which displays a selectable list of all available components.
Resolves https://github.com/Redocly/redocly/issues/9612#issuecomment-2324936729

fix: eject command with no component specified

---

docs/commands/index.md
docs/commands/translate.md
docs/sidebars.yaml

- Adds page for `translate` command
- Sidebar entry in commands group
Note: `--project-dir` option not working as expected -- temporarily removed.

docs: add translate command page

---

docs/commands/translate.md

Adds `--project-dir` option to translate command doc

docs: updating translate doc with project-dir option

---

.changeset/orange-apricots-drop.md
package-lock.json
packages/core/package.json

Fixing deprecated warning for punycode package:
```
(node:48436) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
at node:punycode:3:9
```
Closes: https://github.com/Redocly/redocly-cli/issues/1332

fix: deprecated warning for punycode package

---

.changeset/fresh-cheetahs-love.md
packages/core/src/rules/common/assertions/__tests__/asserts.test.ts
packages/core/src/rules/common/assertions/asserts.ts

Fixing reported issue with camelCase assertion:
```
Small issue in camelCase assertion: single-character lower-case string (e.g. f ) is reported as not camelcase
```

fix: camelCase assertion for single letter

---

.changeset/tiny-boats-check.md
packages/cli/src/cms/api/__tests__/api.client.test.ts
packages/cli/src/cms/api/api-client.ts
packages/cli/src/cms/commands/__tests__/push-status.test.ts
packages/cli/src/cms/commands/__tests__/push.test.ts
packages/cli/src/cms/commands/push-status.ts
packages/cli/src/cms/commands/push.ts

Warn user about planned endpoint sunset.
Currently there is no way to let user know about breaking changes in the endpoints or endpoint deprecation used for specific command.
Lookup for `Sunset` header in responses received from Reunite to notify users if there are resources that is going to deprecate or is already deprecated (but is still functioning).   
*Endpoint is about to be deprecated*
*Endpoint is already deprecated*

feat: report endpoint sunset

---

.changeset/happy-avocados-rule.md
packages/core/src/types/arazzo.ts
packages/core/src/typings/arazzo.ts

Remove support of x-assert extension for spot.
Closes: https://github.com/Redocly/redocly/issues/11345

feat: remove support of x-assert extension for spot

---

.changeset/stupid-suits-deny.md
packages/core/src/bundle.ts
packages/core/src/types/arazzo.ts
packages/core/src/typings/arazzo.ts

Remove x-parameters extension for Spot.
https://github.com/Redocly/redocly/issues/11341

feat: remove x-parameters extension for Spot

---

.changeset/early-ducks-deliver.md
packages/core/src/config/config-resolvers.ts

We use some of `@redocly/openapi-core` util functions in Reunite.
`_importDynamic` is an eval function that is initialized in the root of `config-resolvers` module which violates content security policies in Reunite.
This PR delays `_importDynamic ` init to a later time - avoiding it's initialization in Reunite completely.
https://github.com/Redocly/redocly/issues/11257

chore: delay _importDynamic initialization

---

.changeset/smooth-actors-sneeze.md
packages/core/src/types/arazzo.ts
packages/core/src/typings/arazzo.ts

Removed the support of the `x-inherit` extension for Spot
https://github.com/Redocly/redocly/issues/11346

feat: removed the support of the `x-inherit` extension for Spot

---

.changeset/hip-ducks-hear.md
package-lock.json
packages/cli/package.json

It should fix the next vulnerabilities for the `openapi-starter`:
- https://github.com/Redocly/openapi-starter/security/dependabot/17
- https://github.com/Redocly/openapi-starter/security/dependabot/18
https://app.vanta.com/tests/packages-checked-for-vulnerabilities-v2-records-closed-github-dependabot-high?tab=results

chore: bump `redoc` to the latest

---

docs/rules/no-server-example-com.md
docs/rules/no-unresolved-refs.md
docs/rules/required-string-property-missing-min-length.md
docs/rules/scalar-property-missing-example.md
docs/rules/spec-strict-refs.md
docs/rules/tag-description.md

When using the CLI docs by themselves, they report some broken links. Update them to be relative or fully-qualified.

docs: replace absolute links for a more portable docs set

---

docs/commands/push.md
docs/configuration/index.md
docs/custom-plugins/visitor.md
docs/guides/configure-rules.md
docs/guides/hide-apis.md
docs/guides/hide-specification-extensions.md
docs/guides/replace-servers-url.md
docs/guides/response-contains-property.md
docs/quickstart.md

- Changes admonition type from "attention" to "info"
- Eliminates downstream validation errors on admonition Markdoc tag
Manually verify admonition change in branch preview

docs(all): changes admonition type from 'attention' to 'info'

---

.changeset/tricky-balloons-kick.md
packages/core/src/__tests__/__snapshots__/bundle.test.ts.snap
packages/core/src/__tests__/bundle.test.ts
packages/core/src/__tests__/fixtures/refs/openapi-with-special-names-in-props.yaml
packages/core/src/ref-utils.ts
packages/core/src/resolve.ts

Fixes https://github.com/Redocly/redocly-cli/issues/1765
The original bug was introduced in https://github.com/Redocly/redocly-cli/pull/1747

fix: do not try resolving exteranlValues used as property names

---

.changeset/seven-geckos-behave.md
__tests__/bundle/remove-x-internal/main.yaml
__tests__/bundle/remove-x-internal/redocly.yaml
__tests__/bundle/remove-x-internal/schemas/candy-cane.yaml
__tests__/bundle/remove-x-internal/schemas/cranberry.yaml
__tests__/bundle/remove-x-internal/schemas/popcorn.yaml
__tests__/bundle/remove-x-internal/snapshot.js
packages/core/src/bundle.ts
packages/core/src/decorators/__tests__/remove-x-internal.test.ts
packages/core/src/decorators/common/remove-x-internal.ts

Fixed the `remove-x-internal` decorator, which was not removing the reference in the corresponding discriminator mapping while removing the original $ref.
Fixes https://github.com/Redocly/redocly-cli/issues/1649

fix: clean up the discriminator mapping in the remove-x-internal decorator

---

.changeset/real-chicken-cheat.md
packages/core/src/rules/oas3/__tests__/component-name-unique.test.ts
packages/core/src/rules/oas3/component-name-unique.ts

What: This sets the location on the reported problem & makes the message one line instead of multiple lines.
Why: The `component-name-unique` didn't report any location. That location is specifically useful when using the ignore file. The message is more aligned with the other reports.
How: By using passing the `location` and reporting it instead of just passing the `absolutePointer`.
See updated test code.

fix: component-name-unique rule should report location

---

.changeset/slimy-humans-nail.md
packages/core/src/__tests__/bundle.test.ts
packages/core/src/bundle.ts

Fixed API descriptions bundling. Previously, schemas containing nulls in examples were causing failures.
The original bug was introduced [here](https://github.com/Redocly/redocly-cli/pull/1747).
Discovered the bug while testing the OpenAPI VSCode extension:
```yaml
openapi: 3.1.0
paths: 
/:
get: 
responses: 
200:
content: 
application/json: 
examples: 
Foo:   # <-- if fails when trying to resolve externalValues here
```

fix: do not fail when bundling a description containing null in examples

---

.changeset/dull-kiwis-agree.md
packages/core/src/decorators/common/remove-x-internal.ts

Fixed an issue with the `remove-x-internal` decorator where bundling API descirptions containing discriminators could fail when using **Node.js** v17 or earlier.

chore: fix the remove-x-internal decorator for Node.js v17-

---

.changeset/nervous-bikes-wait.md
packages/core/src/redocly/index.ts

The check inside `isAuthorizedWithRedocly` was incorrect. We were checking for objects, but the argument is actually an array.
Fixes https://github.com/Redocly/redocly-cli/issues/1805

fix: make isAuthorizedWithRedocly recognize valid Redocly tokens

---

.changeset/fuzzy-crews-boil.md
packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
packages/core/src/config/__tests__/utils.test.ts
packages/core/src/config/utils.ts
packages/core/src/utils.ts

Severity of configurable rules could not be overridden without full rule copy:
**base.yaml**
```yaml
rules:
rule/abc:
severity: error
```
**redocly.yaml**
```yaml
extends:
- base.yaml
rules:
rule/abc: warn
```
The above did not work.
Reported by a customer.
Related to https://github.com/Redocly/redocly/issues/12111
Covered with unit test.

fix: resolve problem with severity change for configurable rules

---

.changeset/long-donkeys-bathe.md
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/commands/join.ts

Fixes https://github.com/Redocly/redocly-cli/issues/1196.
Tested locally in `/bin/sh` env and works where it was previously failing.

fix: expand glob before checking API count in join

---

docs/guides/lint-arazzo.md
docs/guides/lint-asyncapi.md
docs/rules/arazzo/criteria-unique.md
docs/rules/arazzo/parameters-unique.md
docs/rules/arazzo/requestBody-replacements-unique.md
docs/rules/arazzo/sourceDescriptions-name-unique.md
docs/rules/arazzo/sourceDescriptions-not-empty.md
docs/rules/arazzo/sourceDescriptions-type.md
docs/rules/arazzo/step-onFailure-unique.md
docs/rules/arazzo/step-onSuccess-unique.md
docs/rules/arazzo/stepId-unique.md
docs/rules/arazzo/workflow-dependsOn.md
docs/rules/arazzo/workflowId-unique.md
docs/rules/async/channels-kebab-case.md
docs/rules/async/no-channel-trailing-slash.md
docs/rules/built-in-rules.md
docs/rules/configure-rules.md
docs/rules/minimal.md
docs/rules/recommended.md
docs/rules/ruleset-templates.md
docs/rules/spot/parameters-not-in-body.md
docs/rules/spot/version-enum.md
docs/sidebars.yaml

CLI rules documentation updates.
Closes: https://github.com/Redocly/redocly-cli/issues/1691
Moved docs update from https://github.com/Redocly/redocly-cli/pull/1697

chore: add cli rules docs

---

.github/workflows/pr-title.yml

This PR adds a GitHub Action to check PR titles.
They should follow this pattern: `<type>[(scope)]: <subject>`.
The goal is to ensure all commit messages follow the same style (see the [contribution guide](https://github.com/Redocly/redocly-cli/blob/125d240465d70a65475ad444032e3762dd13092c/CONTRIBUTING.md?plain=1#L35)).

chore: test check-pr-title

---

.changeset/wild-scissors-rest.md
__tests__/build-docs/build-docs-with-config-option/snapshot.js
__tests__/build-docs/simple-build-docs/snapshot.js
packages/cli/src/commands/build-docs/utils.ts

Hey there,
Using CLI `redocly build-docs`
This always prints the following into `stderr`.
```
Found /Users/(...)/redocly.yaml and using theme.openapi options
Prerendering docs
```
I have many other stuff happening in my project, and generating multiple docs, so this just adds noise & annoyance, whereas it's just (verbose) logs and not errors anyway.

fix: use stdout instead of stderr for simple logs in build-docs

---

.changeset/tender-forks-argue.md
packages/core/src/config/config-resolvers.ts

There is an issue when running the `npx @redocly/cli preview` command when the `@redocly/realm` package is not installed in the project's `node_modules`: it's dependent package cannot be resolved.
This happens because the npx installs both the `@redocly/realm` and it's dependency `@redocly/openapi-core` into a cache directory (`~/.npm/_npx` for mac and linux) but when resolving plugins, only the project directory is considered.
This PR adds the package location to the list of directories to resolve the Realm plugins from.

fix: consider the cli install directory when resolving plugins

---

.changeset/blue-coats-rescue.md
packages/core/src/types/arazzo.ts
packages/core/src/typings/arazzo.ts

Removed support for in: body parameters due to [Arazzo specification updates](https://spec.openapis.org/arazzo/latest.html#parameter-object).

feat: remove support in-body parameter in arazzo

---

.github/workflows/snapshot-release.yaml
CONTRIBUTING.md
benchmark/package.json

- Updated the snapshot release message to make comment in the release PR instead of modifying the description.
- Updated benchmarks.

chore: update snapshot release message

---

.changeset/warm-tips-sit.md
.github/workflows/smoke.yaml
CONTRIBUTING.md
README.md
package-lock.json
package.json
packages/cli/package.json
packages/cli/src/__tests__/commands/push-region.test.ts
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/__tests__/fetch-with-timeout.test.ts
packages/cli/src/__tests__/wrapper.test.ts
packages/cli/src/cms/api/__tests__/api.client.test.ts
packages/cli/src/cms/api/api-client.ts
packages/cli/src/commands/push.ts
packages/cli/src/utils/fetch-with-timeout.ts
packages/core/package.json
packages/core/src/redocly/__tests__/redocly-client.test.ts
packages/core/src/redocly/registry-api.ts
packages/core/src/utils.ts

- bump required node version
- migrate from node-fetch to fetch
- fix punycode Deprecation warning message in Spot but not in CLI itself due to its inner dependencies
- Monorepo run => https://github.com/Redocly/redocly/pull/12932
- push to workflows
- push to github

feat: migrate from node-fetch to native fetch

---

docs/commands/push-status.md

Users who were trying to use the push-status command were getting frustrated because the links on the page describing the org and project slugs currently are broken. The content was removed from our docs site and these links were not updated, so I copied the content into the command doc and removed the broken links.
[#13071 on the docs content board](https://github.com/orgs/Redocly/projects/57?pane=issue&itemId=95114380&issue=Redocly%7Credocly%7C13071#:~:text=to%20404%20error-,%2313071,-Edit)
I ran the content in my local version of the marketing repo to be sure the formatting and links work.

docs(all): adds info for finding org and project slugs to push-status command doc and removes broken links

---

.changeset/dry-candles-lie.md
packages/core/src/types/redocly-yaml.ts

Resolved an issue where overrides for the severity of configurable rules raised warnings when validating the config.
Closes https://github.com/Redocly/redocly-cli/issues/1865
It's a follow-up to https://github.com/Redocly/redocly-cli/pull/1811

fix: validate configurable rules severity overrides correctly in config

---

.changeset/big-kings-sort.md
packages/core/src/rules/arazzo/__tests__/spot-supported-versions.test.ts
packages/core/src/typings/arazzo.ts

Added support for Arazzo version 1.0.1 in Spot validation rules.
Adding it as a enum as it takes some time to adapt tooling and despite on patch Arazzo spec version update - some changes can cause not valid file due to some supported syntax was removed or changed (request-in-body, $message from runtime expression, changes on how we can access outputs from the body response).

feat: added 1.0.1 arazzo version to spot supported versions rule

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Reduce recommended npm version to 9.5 as it has a number of security fixes and compatible with recommended node js version.

chore: reduce recommended npm version

---

CONTRIBUTING.md
__tests__/smoke-plugins/package.json
__tests__/smoke/package.json
benchmark/package.json

- Fixed the CONTRIBUTING guide
- Marked technical package.jsons as private for clarity

chore: update contributing guide and mark technical package.jsons private

---

.changeset/weak-bears-perform.md
__tests__/commands.test.ts
packages/cli/src/commands/build-docs/index.ts

Fixed an issue where the `build-docs` command produced incorrect output.
Fixes https://github.com/Redocly/redocly-cli/issues/1895#issuecomment-2643680046
This fixes an issue introduced in https://github.com/Redocly/redocly-cli/pull/1892
Tested locally, updated the snapshot size.

fix: calculate redoc version correctly in build-docs command

---

.changeset/stale-starfishes-rule.md
packages/cli/src/__tests__/utils.test.ts
packages/core/src/types/overlay.ts
packages/core/src/typings/overlay.ts

related #1246
Provides typings and interfaces for a structured Overlay description per the https://github.com/OAI/Overlay-Specification
Hopefully this is the first step to providing support for this new specification!
Can't wait to see what you build! 
https://github.com/OAI/Overlay-Specification/releases/tag/1.0.0

feat: add typings and interfaces for Overlay Specification v1.0.0

---

.changeset/violet-guests-suffer.md
packages/core/src/rules/oas3/__tests__/no-invalid-media-type-examples.test.ts
packages/core/src/rules/oas3/no-invalid-media-type-examples.ts

Fixed an issue where the `no-invalid-media-type-examples` rule crashed instead of reporting an error when it failed to resolve an example from a $ref.
Fixes https://github.com/Redocly/redocly-cli/issues/1905

fix: make the no-invalid-media-type-examples rule fail gracefully when the example is not resolved from a ref

---

packages/cli/src/index.ts
packages/respect-core/src/handlers/run.ts
packages/respect-core/src/modules/__tests__/test-config-generator/generate-test-config.test.ts
packages/respect-core/src/modules/flow-runner/runner.ts

Improve the respect command integration into CLI.

chore: update respect command handler

---

CONTRIBUTING.md
benchmark/package.json
packages/cli/src/index.ts

Improved perf and updated docs + benchmark setup.

chore: improve performance

---

packages/cli/src/index.ts
packages/respect-core/src/handlers/generate.ts
packages/respect-core/src/modules/__tests__/test-config-generator/generate-test-config.test.ts
packages/respect-core/src/modules/test-config-generator/generate-test-config.ts

Remove `extended` option from `generate-arazzo` command.
This will be the default behavior.
e.g. of generated file =>
```yaml
arazzo: 1.0.1
info:
title: Redocly Museum API
version: 1.1.1
sourceDescriptions:
- name: museum
type: openapi
url: resources/museum.yaml
workflows:
- workflowId: get-museum-hours-workflow
steps:
- stepId: get-museum-hours-step
operationId: $sourceDescriptions.museum.getMuseumHours
successCriteria:
- condition: $statusCode == 200
```

feat: removed extended option from generate-arazzo command

---

jest.config.js
packages/respect-core/src/modules/__tests__/flow-runner/get-server-url.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/prepare-request.test.ts
packages/respect-core/src/modules/description-parser/get-request-data-from-openapi.ts
packages/respect-core/src/modules/flow-runner/get-server-url.ts
packages/respect-core/src/modules/flow-runner/prepare-request.ts
packages/respect-core/src/utils/api-fetcher.ts

As `openapiOperation.servers[0]` already have servers resolved with priority of `Operation--Path--Root` (from higher to lower) we extend it to also resolve complex server url description with variables, `default` value will be selected and resolved in the final server url.
```
- url: https://{region}-server-with-vars.com/v1
description: Regional server
variables:
region:
default: us
enum:
- us
- eu
- asia
```         
Closes: https://github.com/Redocly/redocly/issues/11205
```openAPI.yaml
openapi: 3.1.0
info:
title: Minimal API
version: 1.0.0
security: []
servers:
- url: https://{region}.{task}-server-with-vars.{domain}/v1
description: Regional server
variables:
region:
default: us
enum:
- us
- eu
- asia
task:
default: ping
domain:
default: com
- url: https://top-level-server.com …
```

feat: resolve server url

---

packages/respect-core/src/modules/__tests__/flow-runner/get-server-url.test.ts
packages/respect-core/src/modules/flow-runner/get-server-url.ts

Fixed resolving serverUrl with `x-serverUrl': '$servers.2.url'` syntax.

fix: server selection by index

---

.github/workflows/smoke-rebilly.yaml
.github/workflows/smoke.yaml
.husky/pre-commit
__tests__/smoke/package.json
__tests__/smoke/prepare-smoke.sh
__tests__/smoke/run-smoke.sh
package-lock.json
package.json

- Added a pre-commit hook (prettier + eslint) to improve the developer experience
- Skip Rebilly smoke tests for external contributions (as they will fail anyway due to missing credentials)
- Added Respect smokes
- Added a pnpm smoke

chore: add a precommit hook and improve smoke tests

---

package-lock.json
packages/cli/package.json

`@redocly/cli` was missing a dependency on `@redocly/config`. This adds that dependency so that installing and using `@redocly/cli` using tools like `pnpm` won't fail. Specifically, this is when hoisting is not enabled: https://pnpm.io/npmrc#hoist
https://github.com/Redocly/redocly-cli/blob/b11ded51062c3b9d296e9c81663144a0410a409b/packages/cli/src/utils/miscellaneous.ts#L28

chore: add @redocly/config to @redocly/cli dependencies

---

packages/respect-core/tsconfig.json

Fixed types exporting from respect-core.
No testing needed

fix: add node types to tsconfig in respect-core

---

.changeset/hip-apricots-juggle.md
packages/core/src/rules/arazzo/__tests__/respect-supported-versions.test.ts
packages/core/src/rules/respect/respect-supported-versions.ts
packages/core/src/typings/arazzo.ts
packages/respect-core/src/modules/__tests__/flow-runner/runner/__snapshots__/run-test-file.test.ts.snap
packages/respect-core/src/modules/__tests__/flow-runner/runner/run-test-file.test.ts
packages/respect-core/src/modules/flow-runner/get-test-description-from-file.ts
packages/respect-core/src/modules/flow-runner/runner.ts

Change arazzo supported version validation by adding 1.0.0 version warning but not prevent execution.

fix: change arazzo supported version validation

---

.github/workflows/deploy-s3-sandbox.yaml

Updated S3 sandbox deploymet pipeline (replaced an old caching action).
The failing job: https://github.com/Redocly/redocly-cli/actions/runs/13627145806/job/38086720934?pr=1971
Tested in this PR: https://github.com/Redocly/redocly-cli/actions/runs/13627383886/job/38087432615?pr=1973

chore: update S3 sandbox deploymet pipeline

---

.changeset/light-lizards-play.md
packages/core/src/types/oas3.ts

the `type` keyword should not include the `null` value.
OAS3 uses the `nullable` keyword.
closes #https://github.com/Redocly/redocly-vs-code/issues/48

fix(types): oas schema type definition

---

.changeset/short-mayflies-lay.md
packages/respect-core/src/modules/cli-output/json-logs.ts
packages/respect-core/src/modules/flow-runner/runner.ts
packages/respect-core/src/types.ts

Nested external workflow in json logs were not included and crashed.

fix: nested external workflow in json logs

---

.changeset/red-birds-give.md
.github/CODEOWNERS
packages/core/src/types/oas2.ts

Made the `x-example` property in `oas2` accept any data. Although it should be a primitive, it looks like Redoc supports also objects, so I decided not to restrict it too much.
Also, updated the CODEOWNERS file to require approval from all owners.
Partially resolves https://github.com/Redocly/redocly-vs-code/issues/75
Tested manually.

chore: fix x-example node type in oas2

---

.changeset/green-hairs-suffer.md
.changeset/silver-crews-eat.md
packages/core/src/typings/openapi.ts
packages/respect-core/src/modules/__tests__/arazzo-description-generator/generate-inputs-arazzo-components.test.ts
packages/respect-core/src/modules/__tests__/arazzo-description-generator/generate-workflow-security-inputs.test.ts
packages/respect-core/src/modules/__tests__/arazzo-description-generator/generate-workflow-security-parameters.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/context/__snapshots__/create-runtime-expression-ctx.test.ts.snap
packages/respect-core/src/modules/arazzo-description-generator/generate-arazzo-description.ts
packages/respect-core/src/modules/arazzo-description-generator/generate-inputs-arazzo-components.ts
packages/respect-core/src/modules/arazzo-description-generator/generate-workflow-security-inputs.ts
packages/respect-core/src/modules/arazzo-description-generator/generate-workflow-security-parameters.ts
packages/respect-core/src/modules/arazzo-description-generator/generate-workflows-from-description.ts
packages/respect-core/src/modules/arazzo-description-generator/index.ts
packages/respect-core/src/modules/description-parser/bundle-openapi.ts

Expend Arazzo genration to handle simple cases of securitySchemes (basic, apiKey, bearer) and create `inputs` on `components` level, `parameters` and `inputs` per Workflow.
Autogeneration is still not perfect, but can give more insides about Step security requirements. 
Closes: https://github.com/Redocly/redocly-cli/issues/1961

feat: improve generate-arazzo command output

---

.changeset/rich-falcons-act.md
packages/core/src/rules/common/__tests__/no-invalid-schema-examples.test.ts
packages/core/src/rules/common/no-invalid-schema-examples.ts
packages/core/src/rules/oas2/index.ts
packages/core/src/rules/oas3/index.ts

Fixed the `no-invalid-schema-examples` rule validating nullable OpenAPI 3.0 schemas incorrectly.
Added the check for `null` example in nullable schemas (only valid for OAS3).
Related issue: https://github.com/Redocly/redocly-vs-code/issues/42
Tested in VS Code extension as well.

fix: validate nullable oas3 example correctly

---

.changeset/fast-islands-sell.md
__tests__/respect/consider-severity-in-next-step-execution/__snapshots__/consider-severity-in-next-step-execution.test.ts.snap
__tests__/respect/consider-severity-in-next-step-execution/consider-severity-in-next-step-execution.arazzo.yaml
__tests__/respect/consider-severity-in-next-step-execution/consider-severity-in-next-step-execution.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/call-api-and-analyze-results.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
packages/respect-core/src/modules/flow-runner/call-api-and-analyze-results.ts

Consider severity in the next step execution when onFailure is omitted.

fix(respect-core): consider severity in the next step execution when onFailure is omitted

---

README.md

Updated README to mention out new products instead of the old ones.

docs: update readme to point to Reunite

---

packages/core/README.md

Config is indeed required when linting from openapi-core.

docs: update readme in openapi-core

---

.changeset/happy-impalas-matter.md
packages/cli/src/index.ts
packages/respect-core/src/handlers/generate.ts

- `output-file` is not mandatory, but can't be empty when provided.
- error will be returned if not valid `output-file` provided (e.g. existing directory instead of file).
Closes: https://github.com/Redocly/redocly-cli/issues/1990

fix(respect): generate-arazzo with provided folder path

---

README.md
docs/commands/generate-arazzo.md
docs/commands/index.md
docs/commands/push.md
docs/commands/respect.md
docs/guides/hide-specification-extensions.md
docs/guides/replace-servers-url.md
docs/installation.md

Add @latest to all npx redocly cli commands to avoid client issues with cashed npx packages.

docs: add latest to all npx redocly cli commands

---

package-lock.json
package.json
packages/cli/package.json
packages/cli/src/__tests__/fetch-with-timeout.test.ts
packages/cli/src/utils/fetch-with-timeout.ts
packages/cli/src/utils/proxy-agent.ts
packages/core/package.json
packages/core/src/index.ts
packages/core/src/utils.ts

- Moved https-proxy-agent out of the openapi-core package
- Added browser stubs for "node:url" and    "node:module"
- Renamed script clean -> clear for clarity

refactor: move https-proxy-agent out of the openapi-core package

---

.prettierignore
benchmark/make-test-command.sh

- Made historical versions performance benchmark to fail on real failures.
- Updated prettier to ignore changeset config file.
Discovered in a Release pipeline run: https://github.com/Redocly/redocly-cli/pull/2056

chore: update benchmark setup

---

CONTRIBUTING.md
README.md
__tests__/smoke/pre-built/redoc.html

- Clarified required Node.js version.
- Updated smoke `build-docs` snapshots (since styled-components' new version has been released).
Related: https://github.com/Redocly/redocly-cli/pull/1988

docs: clarify the Node.js version requirements

---

packages/core/src/types/redocly-yaml.ts

Error on the `spec` rule in Redocly config.
This is a follow-up to https://github.com/Redocly/redocly-cli/pull/2080

chore: remove the spec rule support in redocly.yaml

---

packages/core/src/rules/respect/x-security-schema-required-values.ts
packages/core/src/typings/arazzo.ts
packages/respect-core/src/consts.ts
packages/respect-core/src/modules/__tests__/config-parser/get-security-parameters.test.ts
packages/respect-core/src/modules/config-parser/get-security-parameters.ts
packages/respect-core/src/modules/flow-runner/call-api-and-analyze-results.ts
packages/respect-core/src/modules/flow-runner/resolve-x-security-parameters.ts
packages/respect-core/src/utils/__tests__/api-fetcher.test.ts
packages/respect-core/src/utils/__tests__/digest-auth/generate-digest-auth-header.test.ts
packages/respect-core/src/utils/__tests__/digest-auth/parse-www-authenticate-header.test.ts
packages/respect-core/src/utils/api-fetcher.ts
packages/respect-core/src/utils/digest-auth/generate-digest-auth-header.ts
packages/respect-core/src/utils/digest-auth/parse-www-authenticate-header.ts

Adding support for `digest` auth scheme.
```
x-security:
- scheme:
type: http
scheme: digest
values:
username: dimaananskyi
password: secret
```
This changes the way fetch performed when Step have `x-security` with `digest` scheme described.
In this case fetch will be called two times during Step execution to establish required data exchange.
`Authorization` header for `digest` will override other `Authorization` headers, that was described by other `x-security` schemes.

feat(respect): implementing digest auth with x-security

---

docs/@v1/decorators.md
docs/@v1/guides/lint-arazzo.md
docs/@v1/guides/migrate-from-spectral.md
docs/@v1/rules.md
docs/@v2/decorators.md
docs/@v2/guides/lint-arazzo.md
docs/@v2/guides/migrate-from-spectral.md
docs/@v2/rules.md

The links are no longer valid. I think Github has changed the interface and we cannot refer to a specific type of template via a url like we did before: 
https://github.com/Redocly/redocly-cli/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=

docs: fix wrong issue links

---

__tests__/respect/x-security-basic-auth/__snapshots__/x-security-basic-auth.test.ts.snap
__tests__/respect/x-security-bearer-auth/__snapshots__/x-security-bearer-auth.test.ts.snap
__tests__/respect/x-security-oauth2-auth/__snapshots__/x-security-oauth2-auth.test.ts.snap
__tests__/respect/x-security-on-workflow-level-merged-to-steps/__snapshots__/x-security-on-workflow-level-merged-to-steps.test.ts.snap
__tests__/respect/x-security-open-id-connect-auth/__snapshots__/x-security-open-id-connect-auth.test.ts.snap
__tests__/respect/x-security-resolve-scheme-name/__snapshots__/x-security-resolve-scheme-name.test.ts.snap
__tests__/respect/x-security-scheme-apply-order/__snapshots__/x-security-scheme-apply-order.test.ts.snap
packages/respect-core/src/modules/__tests__/config-parser/get-security-parameters.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/resolve-x-security-parameters.ts.test.ts
packages/respect-core/src/modules/context-parser/get-security-parameters.ts
packages/respect-core/src/modules/flow-runner/context/create-test-context.ts
packages/respect-core/src/modules/flow-runner/prepare-request.ts
packages/respect-core/src/modules/flow-runner/resolve-x-security-parameters.ts
packages/respect-core/src/types.ts

- Hide generated by x-security Authorization headers (`basic`, `bearer`, `oath2`, `openIdConnect` )
- Hide header for `digest` only when username value is an input with format:`password`
- Hide params for `apiKey` only when value is an input with format:`password`

feat(respect): hide in logs authorization header generated by x-security

---

packages/respect-core/src/modules/flow-runner/prepare-request.ts
packages/respect-core/src/utils/api-fetcher.ts

Fixed the issue when resolving scheme for digest schemeName x-security.

fix: resolve scheme from digest schemeName

---

packages/cli/src/utils/telemetry.ts

Fixed wrong CJS-style imports that were working in dev mode but failing when running a bundled package.
Tested manually. Does not require automated tests.

chore: fix CJS imports

---

.changeset/thick-planets-fail.md
__tests__/commands.test.ts
__tests__/fixtures/constructor-property/openapi.yaml
__tests__/fixtures/constructor-property/snapshot.txt
packages/core/src/resolve.ts
packages/core/src/rules/common/no-required-schema-properties-undefined.ts
packages/core/src/rules/common/scalar-property-missing-example.ts
packages/core/src/rules/common/struct.ts
packages/core/src/types/index.ts
packages/core/src/utils.ts
packages/core/src/walk.ts

Because we used regular objects we mistakenly were getting `constructor` property validated incorrectly.
Fixes https://github.com/Redocly/redocly-cli/issues/2104
Added e2e.

fix: fixed the wrong validation of constructor property

---

package.json

Apply ESLint only to `.ts` files.
Fixes https://github.com/Redocly/redocly-cli/actions/runs/15565514469/job/43828500912

chore: fix the lint-staged setup

---

.changeset/smart-bees-deny.md
package-lock.json
packages/cli/src/__tests__/wrapper.test.ts
packages/cli/src/commands/auth.ts
packages/cli/src/utils/telemetry.ts
packages/cli/src/wrapper.ts
packages/core/package.json
packages/core/src/config/types.ts

CLI should consider [residency setting](https://redocly.com/docs/realm/config/residency) from redocly.yaml during login and token verification process.
Closes: https://github.com/Redocly/redocly/issues/16251

fix(project): cli consider residency setting from Redocly config file

---

docs/@v2/configuration/api.yaml
docs/@v2/configuration/apis.md
docs/@v2/configuration/index.md
docs/@v2/guides/migrate-from-redoc-cli.md

- Removed assuming `@latest` version in the `apis` section
- Removed `theme` section
- Added `extends` section in the `apis` config
Resolves https://github.com/Redocly/redocly-cli/issues/1660

docs: update per-API settings for CLI v2

---

.changeset/clean-grapes-sleep.md
packages/cli/src/index.ts

Added environment variable support for CLI arguments using Yargs `env()` method to parse environment variables with matching prefixes.
Suggested prefix format is `REDOCLY_CLI_{COMMAND_NAME}`.
We can have single `REDOCLY_CLI` prefix, but this can be confusing when args name is the same for different commands in a single environment, but you need to use different values.
Closes: https://github.com/Redocly/redocly-cli/issues/1796

feat(cli): add environment variable support for CLI commands

---

docs/@v2/guides/migrate-from-redoc-cli.md

corrects typo in name of new parameter name
Current docs say:
> Replace your existing `--options.theme.*` settings with a new prefix: `--theme.options.theme.*`.
But then the example code right below it shows:
```
redocly build-docs --theme.openapi.theme.sidebar.width='300px' openapi.yaml
```
The CLI help for `redocly build-docs` show the correct parameter format is `--theme.openapi.theme.*` not `--theme.options.theme`
```
--theme              Redoc theme.openapi configuration. Use dot notation,
e.g. theme.openapi.nativeScrollbars
```

docs: update migrate-from-redoc-cli.md

---

docs/@v2/guides/migrate-to-v2.md

Updated migration guide following https://github.com/Redocly/redocly-cli/pull/2172.

docs: update migration guide

---

packages/core/src/config/__tests__/load.test.ts
packages/core/src/config/load.ts
packages/core/src/index.ts

Removed the deprecated `processRawConfig` from `loadConfig`. 
All the arguments that `processRawConfig` was receiving before, are in the `Config` instance now. 
There should be no user impact (expect for internal usage).

chore!: remove processRawConfig from loadConfig

---

benchmark/make-test-command.sh

Fixed  performance benchmark by adding the installation step in the api-definitions repo.
Related fix: https://github.com/Rebilly/api-definitions/pull/1902

chore: fix performance benchmark by adding the installation step

---

packages/core/src/rules/__tests__/spec-ruleset.test.ts
resources/petstore-with-errors.yaml

One test is slow as example.com responds very slow.

chore: speed up test by removing slow external call

---

.changeset/funny-mayflies-knock.md
packages/cli/src/__tests__/commands/join.test.ts
packages/cli/src/__tests__/wrapper.test.ts
packages/cli/src/commands/join.ts
packages/cli/src/commands/split/index.ts
packages/cli/src/commands/split/types.ts
packages/core/src/bundle.ts
packages/core/src/config/__tests__/config-resolvers.test.ts
packages/core/src/config/__tests__/config.test.ts
packages/core/src/config/config.ts
packages/core/src/index.ts
packages/core/src/lint.ts
packages/core/src/oas-types.ts
packages/core/src/rules/common/scalar-property-missing-example.ts
packages/core/src/rules/oas3/no-server-variables-empty-enum.ts
packages/core/src/types/redocly-yaml.ts

Addressing FIXMES before 2.0 GA: 
- Replaced `SpecVersion`, `SpecMajorVersion`, `OPENAPI3_METHOD`, and `OPENAPI3_COMPONENT` enums with types
- Removed `OasVersion` enum

refactor!: replace enums with types

---

.changeset/pre.json
.github/workflows/release.yaml

Exiting the changeset pre mode. This is the last change before 2.0 GA.
Docs: https://github.com/changesets/changesets/blob/main/docs/prereleases.md

chore: exit the changeset pre mode

---

packages/core/src/rules/common/no-required-schema-properties-undefined.ts

Improved the `no-required-schema-properties-undefined` rule $refs resolver.
Follow up to https://github.com/Redocly/redocly-cli/pull/2226
Tested locally

hotfix: improve the no-required-schema-properties-undefined rule ref resolver

---

README.md
docs/@v2/guides/migrate-to-v2.md

Updated the migration guide to highlight the config file name changes.
Related: https://github.com/Redocly/openapi-starter/pull/81

docs: update the v2 migration guide

---

.changeset/quiet-experts-hope.md
packages/respect-core/src/modules/__tests__/flow-runner/runner/resolve-workflow-context.test.ts
packages/respect-core/src/modules/flow-runner/runner.ts

Ensure `externalRefResolver`  and `skipLint` options are correctly passed to nested workflow contexts.

fix: pass externalRefResolver to nested workflow context

---

.changeset/purple-tips-fry.md
__tests__/build-docs/build-docs-with-disabled-search/config-with-alias.yaml
__tests__/build-docs/build-docs-with-disabled-search/config.yaml
__tests__/build-docs/build-docs-with-disabled-search/openapi.yaml
__tests__/build-docs/build-docs-with-disabled-search/snapshot.txt
__tests__/commands.test.ts
packages/cli/src/commands/build-docs/index.ts
packages/cli/src/commands/build-docs/utils.ts

Fixed an issue where the `openapi` config options were ignored when running the `build-docs` command.
Resolves https://github.com/Redocly/redocly-cli/issues/2237

fix: correctly apply the openapi config options in build-docs

---

.changeset/wise-jars-suffer.md
__tests__/helpers.ts
__tests__/respect/consider-severity-in-next-step-execution/__snapshots__/consider-severity-in-next-step-execution.test.ts.snap
__tests__/respect/implicit/__snapshots__/implicit.test.ts.snap
__tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
__tests__/respect/mask-input-secrets/__snapshots__/mask-input-secrets.test.ts.snap
__tests__/respect/outputs-access-syntax-variations/__snapshots__/outputs-access-syntax-variations.test.ts.snap
__tests__/respect/replacements/__snapshots__/replacements.test.ts.snap
__tests__/respect/reusable-components/__snapshots__/reusable-components.test.ts.snap
__tests__/respect/severity-error-level/__snapshots__/severity-error-level.test.ts.snap
__tests__/respect/severity-off-level/__snapshots__/severity-off-level.test.ts.snap
__tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap
__tests__/respect/x-security-api-key-auth/__snapshots__/x-security-api-key-auth.test.ts.snap
__tests__/respect/x-security-basic-auth/__snapshots__/x-security-basic-auth.test.ts.snap
__tests__/respect/x-security-bearer-auth/__snapshots__/x-security-bearer-auth.test.ts.snap
__tests__/respect/x-security-oauth2-auth/__snapshots__/x-security-oauth2-auth.test.ts.snap
__tests__/respect/x-security-on-workflow-level-merged-to-steps/__snapshots__/x-security-on-workflow-level-merged-to-steps.test.ts.snap
__tests__/respect/x-security-open-id-connect-auth/__snapshots__/x-security-open-id-connect-auth.test.ts.snap
__tests__/respect/x-security-resolve-scheme-name/__snapshots__/x-security-resolve-scheme-name.test.ts.snap
__tests__/respect/x-security-scheme-apply-order/__snapshots__/x-security-scheme-apply-order.test.ts.snap
packages/respect-core/src/modules/__tests__/flow-runner/call-api-and-analyze-results.test.ts
packages/respect-core/src/modules/__tests__/logger-output/mask-secrets.test.ts
packages/respect-core/src/modules/logger-output/display-checks.ts
packages/respect-core/src/modules/logger-output/mask-secrets.ts
packages/respect-core/src/utils/api-fetcher.ts

Respect verbose logs to show `Response headers`.
JSON logs example:
```json
"response": {
"statusCode": 200,
"body": {
"fox": "🦊",
"name": "fox",
"token": "********_token",
"access_token": "********",
"accessToken": "********",
"id_token": "********",
"AccessToken": "tttt",
"idToken": "44444",
"nested": {
"access-token": "iikikikik",
"password": "********"
}
},
"headers": {
"connection": "keep-alive",
"content-length": "267",
"content-type": "application/json; charset=utf-8",
"date": "Wed, 20 Aug 2025 15:57:23 GMT",
"etag": "W/\"10b-lfhzU7sGBlghKk8S2Fkue5Urako\"",
"keep-alive": "timeout=5",
"set-cookie": "accessToken=********; Max-Age=3600; Path=/; Expires=Wed, 20 Aug 2025 16:57:23 GMT; HttpOnly; SameSite=Strict",
"x-powered-by": "Express"
},
"time": 2
},
```
Har logs:
```
"response": { …
```

feat: respect verbose logs to show response headers

---

packages/core/src/bundle.ts
packages/core/src/dequal.ts
packages/core/src/index.ts
packages/core/src/utils.ts

Export AsyncAPI descriptions types to be able to refer to them externally and slightly rearranged exports.

chore: export AsyncAPI types externally

---

.changeset/spotty-trains-bake.md
packages/cli/src/__tests__/utils.test.ts
packages/cli/src/utils/miscellaneous.ts
packages/core/src/utils.ts

Make wildcard pattern params work in CLI.
Fixes #2261 
Run any command accepting multiple files by passing a wildcard format param.

fix: resolve wildcard pattern params from CLI

---

packages/cli/src/__tests__/commands/generate-arazzo.test.ts

Two files were created on local machine tests run: 
That was a side effect of not mocked fs operation for generate-arazzo tests.

chore: mocked fs operations for generate arazzo tests
