README.md
RULES.md

This has more detailed examples of configuration options.
It is pending the change/rename to `excludedPaths` for one config option.  Merge after that change is ready.

docs: Improve the docs about config options

---

src/.openapi-cli.yaml
src/__tests__/validate.test.js
src/context.js
src/resolver.js
src/traverse.js

Easier to check by commits
I left a few **FIXME**, would be great to fix those or at least open issues.

fix: fix resolving local references in external resources

---

.eslintrc.yml
src/__tests__/data/external.yaml
src/__tests__/data/index.yaml
src/__tests__/resolver.test.js
src/cli/index.js
src/context.js
src/error/default.js
src/error/index.js
src/resolver.js
src/traverse.js
src/utils/__tests__/index.test.js
src/utils/index.js
src/visitors/bundler.js
src/yaml/index.js

You can check commit by commit.
Notable changes:
- Support transitive refs
- Fixed URL paths resolution
@knidarkness, please, review carefully and test a bit if you can! Thanks!

fix: support transitive refs

---

src/traverse.js
src/types/OpenAPIDiscriminator.js
src/visitors/bundler.js
src/visitors/rules/structural/noRefSiblings.js

@knidarkness review it, pleae 🙈 
It's super hacky but we need it only for mappings so I'm more or less OK with it...

fix: visit and bundle discriminator mappings

---

README.md
RULES.md
docs/CUSTOM_VISITORS.md
docs/TRANSFORMERS.md
src/cli/index.js
src/visitors/rules/structural/validateAuthorizationCodeOpenAPIFlow.js
src/visitors/rules/structural/validateClientCredentialsOpenAPIFlow.js
src/visitors/rules/structural/validateImplicitOpenAPIFlow.js
src/visitors/rules/structural/validateOpenAPIOperation.js
src/visitors/rules/structural/validatePasswordOpenAPIFlow.js

Preview Docs command docs

---

src/.redocly.yaml
src/traverse.js
src/types/OpenAPIEncodingsMap.js
src/types/OpenAPIMediaObject.js
src/types/index.js
src/visitors/rules/semantic/uniqueParameterNames.js

Fix bunch of rules

---

package-lock.json
package.json
src/yaml/index.js

feat: truncate long lines in error frames

---

src/traverse.js
src/types/OAS2/OAS2Schema.js
src/types/OAS3/OpenAPISchema.js
src/visitors/rules/oas2-structural/validateOAS2Schema.js
src/visitors/rules/structural/validateOpenAPISchema.js

fix: allow more complex logic for property types & fix additionalProperties type

---

.gitignore
src/format/format.ts

handle invalid severity value & provide friendly error message

---

package.json

chore: add engines & engineStrict to package.json

---

src/config/config.ts

Fixes https://github.com/Redocly/openapi-cli/issues/76

fix: throw on duplicated plugin ids

---

src/rules/common/path-params-defined.ts

fix: extended regex path adding dot

---

package-lock.json
packages/cli/package.json
packages/cli/src/assert-node-version.ts
packages/cli/src/index.ts
packages/cli/src/utils.ts

fix: assert node version

---

packages/cli/src/index.ts

- Use sentences with punctuation.
- Consistent casing.
- Fix a vs. an.

chore: improve consistency in inline help

---

packages/core/src/walk.ts

fix: check node for null before running visitor

---

packages/core/src/walk.ts

Reverts Redocly/openapi-cli#200

Revert "fix: check node for null before running visitor"

---

.github/workflows/dockerhub.yaml
Dockerfile
README.md

Add a Dockerfile to allow running the openapi-cli tool in a docker container.
fixes #245
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/redocly/openapi-cli/247)

feat: add Dockerfile

---

package-lock.json
packages/cli/src/index.ts
packages/core/src/redocly/index.ts

fix https://github.com/Redocly/openapi-cli/issues/258

fix: move cli login error stacktrace under --verbose flag

---

packages/cli/package.json

Fixes https://github.com/Redocly/openapi-cli/issues/231
Thanks, @mjpieters for figuring it out 👏

fix: fix preview-docs hot reloading

---

packages/core/src/config/config.ts
packages/core/src/index.ts
packages/core/src/resolve.ts

This change is about having the ability to use openapi-core on the client.

fix: fixes for fs lib to be able to use core on client

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade library to next version

chore: v1.0.0-beta.46

---

packages/core/src/types/oas3_1.ts

Remove unused keywords in openapi 3.1

fix: remove unused keywords

---

__tests__/operation-operationId-in-callback/.redocly.yaml
__tests__/operation-operationId-in-callback/openapi.yaml
__tests__/operation-operationId-in-callback/snapshot.js
packages/core/src/rules/common/operation-operationId.ts

fix: warning when operation-operationId not in callbacks

---

.github/workflows/sync.yml

Docs sync functionality will push changes directly into the destination repo's master branch.
Previously - PR was creating.

chore: changed docs sync flow

---

.github/pull_request_template.md

chore: added security section into pull request template

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.54

---

.github/workflows/deploy.yaml
scripts/archive-and-upload-bundle.js

CD: upload to AWS sandbox S3 bucket

chore: CD - upload to AWS sandbox S3 bucket

---

packages/core/src/index.ts

Export bundleDocument for usage in openapi-vscode
- [] Tested with redoc/reference-docs/workflows
- [] Security impact of change has been considered
- [] Code follows company security practices and guidelines

chore: export bundleDocument for usage in openapi-vscode

---

docs/index.md

Added information about openapi-cli benefits and advantages

Docs: added information about openapi-cli benefits and advantages

---

.github/workflows/deploy.yaml
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.55

---

packages/core/src/__tests__/lint.test.ts
packages/core/src/index.ts
packages/core/src/lint.ts
packages/core/src/rules/common/no-ambiguous-paths.ts
packages/core/src/types/redocly-yaml.ts

Add function for lint .redocly config file.
In the near future, we should add the CLI command for it. And improve types.

feat: add function for lint redocly config file

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Update version to v1.0.0-beta.56

chore: v1.0.0-beta.56

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json
packages/core/src/redocly/index.ts

fix: simplify login check query

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.58

---

docs/commands/join.md

Docs: revised join command

---

packages/core/src/redocly/index.ts

add an optional parameter for the set name of the query in authorize function.

chore:add optional parameter to auth

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.59

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to `v1.0.0-beta.60`

chore: v1.0.0-beta.60

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.61

chore: v1.0.0-beta.61

---

docs/commands/split.md

Docs: revised split command

---

docs/commands/stats.md

Docs: revised stats command

---

__tests__/bundle/max-problems-argument/bar.yaml
__tests__/bundle/max-problems-argument/foo.yaml
__tests__/bundle/max-problems-argument/snapshot.js
__tests__/index.test.ts
packages/cli/src/commands/bundle.ts

closes https://github.com/Redocly/openapi-cli/issues/371

fix: bundle command doesn't work properly --max-problems 

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.62

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
docs/resources/built-in-rules.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.66

---

packages/cli/src/commands/preview-docs/preview-server/preview-server.ts

Fixes [#423](https://github.com/Redocly/openapi-cli/issues/423) [#424](https://github.com/Redocly/openapi-cli/issues/424) 
https://user-images.githubusercontent.com/9461457/139879901-84f3e223-94c1-4023-b029-1ff9f3a973d6.mov

fix: hot reloading + page refresh for section pagination

---

packages/core/__tests__/__snapshots__/bundle.test.ts.snap
packages/core/__tests__/bundle.test.ts
packages/core/__tests__/fixtures/refs/hosted.yaml
packages/core/src/bundle.ts
packages/core/src/ref-utils.ts

Fixes [#281](https://github.com/Redocly/openapi-cli/issues/281)

fix: resolve fetching of hosted schema on windows

---

packages/core/src/rules/oas3/__tests__/no-server-trailing-slash.test.ts
packages/core/src/rules/oas3/no-server-trailing-slash.ts

fix: should not throw error when server url is root

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.69

---

docs/changelog.md
docs/commands/bundle.md
docs/commands/lint.md

changelog and docs for 1.0.0-beta.69

chore: add docs for 1.0.0-beta.69

---

README.md

Update README: CLI local usage

chore: docs for cli local usage

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.70

chore: v1.0.0-beta.70

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.71

chore: v1.0.0-beta.71

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.72

chore: v1.0.0-beta.72

---

packages/core/src/__tests__/lint.test.ts
packages/core/src/types/oas3_1.ts

fix: https://github.com/Redocly/openapi-cli/issues/442

fix: "const" is not handled correctly in lint

---

packages/core/src/config/config.ts

chore: add one more internal domain fix

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.74

chore: v1.0.0-beta.74

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.75

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.76

chore: v1.0.0-beta.76

---

package.json
scripts/archive-and-upload-bundle.js

Helper script for local ref docs deployment.

chore: helper script for local dev

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.77

---

__tests__/bundle/bundle-lint-format/json-format-snapshot.js
docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.78

chore: v1.0.0-beta.78

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.79

chore: v1.0.0-beta.79

---

package.json

chore: ts build watcher

---

packages/cli/src/index.ts

Minor refactor for CLI commands handlers

chore: minor refactor for cli commands handlers

---

__tests__/bundle/primitive-types/snapshot.js
packages/core/src/__tests__/js-yaml.test.ts
packages/core/src/js-yaml/index.ts

fix: converts date-time

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.80

chore: v1.0.0-beta.80

---

package-lock.json
packages/cli/package.json
packages/cli/src/commands/push.ts
packages/core/src/redocly/registry-api.ts

feat: working behind proxy

---

packages/cli/src/commands/split/__tests__/index.test.ts
packages/cli/src/commands/split/index.ts
packages/cli/src/commands/split/types.ts
packages/cli/src/utils.ts
packages/core/src/index.ts

chore: try to simplify

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Upgrade version to v1.0.0-beta.81

chore: v1.0.0-beta.81

---

package-lock.json
packages/cli/package.json
packages/cli/src/commands/push.ts
packages/core/src/redocly/registry-api.ts

Closes #555 
Reverting the changes introduced in https://github.com/Redocly/openapi-cli/pull/531

fix: cannot find module https-proxy-agent #555

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Update to version v1.0.0-beta.82

chore: v1.0.0-beta.82

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Update to version v1.0.0-beta.83

chore: v1.0.0-beta.83

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Chore/v1.0.0 beta.84

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

chore: v1.0.0-beta.85

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

- Pitch change redocly config structure: allow `redocly.yaml` file name ([MR](https://github.com/Redocly/openapi-cli/pull/557))
- Detect parameters without schema or content fields ([MR](https://github.com/Redocly/openapi-cli/pull/583) / [issue](https://github.com/Redocly/openapi-cli/issues/568))
- Support redocly registry at .com domain ([MR](https://github.com/Redocly/openapi-cli/pull/561))

Chore/v1.0.0 beta.86

---

packages/cli/src/__tests__/commands/push-transformPush.test.ts
packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts
packages/cli/src/index.ts
packages/core/src/config/config.ts
packages/core/src/config/load.ts

Pitch [redocly.yaml structure](https://intranet.redoc.ly/roadmap/tooling/2022-02/redocly-yaml/)
Shorten the `push` command.

feat: add new syntax for the push command

---

packages/core/__tests__/utils.ts
packages/core/__tests__/walk.test.ts
packages/core/src/types/oas2.ts

Fix traversal order and added a test
Fixes https://github.com/Redocly/openapi-cli/issues/542

fix: resolve an issue with no-path-parameter rule reporting false-positives

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

- Fixed terser crash in client-site bundles due to `process.env` assignment.
- Fixed an issue with `no-path-parameter` rule reporting false-positives.

chore: v1.0.0-beta.87

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

- https://github.com/Redocly/openapi-cli/pull/594
- https://github.com/Redocly/openapi-cli/pull/597

chore: chore/v1.0.0-beta.89

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

- https://github.com/Redocly/openapi-cli/pull/604
- https://github.com/Redocly/openapi-cli/pull/590

Chore/v1.0.0 beta.90

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

- https://github.com/Redocly/openapi-cli/pull/603
- https://github.com/Redocly/openapi-cli/issues/560
- https://github.com/Redocly/openapi-cli/pull/610
- https://github.com/Redocly/openapi-cli/issues/260

Chore/1.0.0 beta.91

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

- https://github.com/Redocly/openapi-cli/pull/489
- https://github.com/Redocly/openapi-cli/pull/614
- https://github.com/Redocly/openapi-cli/pull/613

chore: 1.0.0-beta.92

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

https://github.com/Redocly/openapi-cli/pull/622

chore: v1.0.0-beta.93

---

packages/core/__tests__/bundle.test.ts
packages/core/__tests__/fixtures/extension.js
packages/core/__tests__/ref-utils.test.ts
packages/core/__tests__/utils.ts
packages/core/src/benchmark/benches/recommended-oas3.bench.ts
packages/core/src/benchmark/utils.ts
packages/core/src/bundle.ts
packages/core/src/config/all.ts
packages/core/src/config/builtIn.ts
packages/core/src/config/config.ts
packages/core/src/config/index.ts
packages/core/src/config/load.ts
packages/core/src/config/minimal.ts
packages/core/src/config/recommended.ts
packages/core/src/config/types.ts
packages/core/src/config/utils.ts
packages/core/src/index.ts
packages/core/src/lint.ts
packages/core/src/redocly/index.ts
packages/core/src/redocly/redocly-client-types.ts
packages/core/src/redocly/registry-api.ts
packages/core/src/resolve.ts
packages/core/src/rules/oas2/__tests__/spec/utils.ts
packages/core/src/rules/oas3/__tests__/spec/spec.test.ts
packages/core/src/rules/oas3/__tests__/spec/utils.ts
packages/core/src/utils.ts

Refactor config part of code.
**Structure**
```
- index.ts
- utils.ts
- types.ts
- other existing files
```
Also fixed all imports

chore: refactor config

---

packages/core/src/config/__tests__/config.test.ts

Unit tests for function `getMergedConfig` (specifically to cover case fixed in #622).

chore: add test for https://github.com/Redocly/openapi-cli/pull/622

---

__tests__/lint/assertions/description.md
__tests__/lint/assertions/openapi.yaml
packages/core/src/rules/common/assertions/utils.ts

Resolvable scalars were not working with assertions.
Fixes https://github.com/Redocly/openapi-cli/issues/645
TODO:

fix: resolvable scalars not working with asserts

---

package.json
packages/cli/src/__tests__/commands/bundle.test.ts
packages/core/src/config/__tests__/load.test.ts

chore: fix jest config

---

packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts
packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
packages/core/src/config/__tests__/config-resolvers.test.ts
packages/core/src/config/__tests__/config.test.ts
packages/core/src/config/config-resolvers.ts
packages/core/src/config/config.ts
packages/core/src/config/types.ts
packages/core/src/config/utils.ts

Fixes pushing config files from extends

fix: push remote configs from extends

---

packages/core/src/types/oas2.ts
packages/core/src/types/oas3.ts
packages/core/src/types/oas3_1.ts
packages/core/src/types/redocly-yaml.ts
packages/core/src/typings/openapi.ts
packages/core/src/typings/swagger.ts

Changes regarding https://github.com/Redocly/reference-docs/pull/527
New option `schemaDefinitionsTagName` and schema extension `x-tags`
https://github.com/Redocly/reference-docs/pull/527

chore: add schema generation typings

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

chore: declare x-hideTryItPanel extension typings (https://github.com/Redocly/redocly-cli/pull/687)
chore: add schema generation typings (https://github.com/Redocly/redocly-cli/pull/690)

chore: v1.0.0 beta.98

---

packages/core/src/types/oas3.ts

add `addinionalItems` to types for Openapi 3.0. 
related to https://github.com/Redocly/redoc/pull/2018

chore: add additionalItems to OpenApi 3.0

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

feat: new `response-contains-header` & `response-contains-property` built-in rules (#537) 
chore: sync options to features.openapi (#693) 
feat: added bundle option to keep url references (#688)
chore: set code coverage threshold & reorganize tests (#695)
chore: add missing array types for 3.1 (#694)
fix: escape symbols in the samples lang name (#703) 
feat: new rule `scalar-property-missing-example` (#705)  
fix: coverage action not fail when UT fail (#706) 
chore: add additionalItems to OpenApi 3.0 (#707)

v1.0.0-beta.99

---

packages/cli/src/commands/split/__tests__/index.test.ts

Fix some unit tests for the split command.

chore: update split test

---

docs/resources/rules/assertions.md
packages/core/src/__tests__/lint.test.ts
packages/core/src/types/oas3.ts

Fix the NamedCallbacks and Callback types.
Fix #664

fix: update callback types

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

chore: update split test (#712)
fix: update callback types(#713)
fix: allow scalar property with falsy values (#717)

chore: v1.0.0 beta.100

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

feat: join multiple files with same tags #722 
[INTERNAL] chore: test coverage threshold #709 
feat: requireOne assertion #719 
chore: fix array items types and sync redocly configuration options #715
chore: add showSecuritySchemeType typing #698

chore: v1.0.0beta.101

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/cli/src/commands/join.ts
packages/core/package-lock.json
packages/core/package.json

chore: v1.0.0 beta.102

---

packages/core/src/__tests__/lint.test.ts
packages/core/src/types/redocly-yaml.ts
packages/core/src/utils.ts

Improve config types for VS Code and CLI validation.
Connected to #720

fix: improve types for config

---

docs/changelog.md

Updated changelog.md according to info about failed build

docs: update changelog

---

packages/cli/src/__tests__/commands/lint.test.ts
packages/core/src/lint.ts

Fixed flaky test after #720 merge

fix: failed test

---

.github/workflows/deploy-s3-sandbox.yaml
__tests__/commands.test.ts
__tests__/helpers.ts
__tests__/webpack-bundle.test.ts
__tests__/webpack-bundle/bundle/.redocly.yaml
__tests__/webpack-bundle/bundle/openapi.yaml
__tests__/webpack-bundle/bundle/snapshot.js
__tests__/webpack-bundle/lint/.redocly.yaml
__tests__/webpack-bundle/lint/openapi.yaml
__tests__/webpack-bundle/lint/snapshot.js
package-lock.json
package.json
webpack.config.ts

Update webpack to `lts` version according to few vulnerabilities.
Close #725

chore: update webpack to version5

---

package.json
webpack.config.ts

chore: optimize webpack build

---

docs/resources/custom-rules.md
packages/core/src/rules/ajv.ts
packages/core/src/walk.ts

Fixes wrong types for **ctx.resolve**.

chore: fix typing and update docs on `ctx.resolve`

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

fix: bug with invalid config file path  #769

chore: v1.0.0-beta.105

---

packages/core/src/resolve.ts

Fix #481 . Replace \r\n from source file.

fix: multiline md with \r\n

---

packages/core/src/redocly/registry-api.ts

chore: added redocly_environment env

---

.github/workflows/tests.yaml
package-lock.json
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/utils.ts

Add notification to `redocly-cli` about the new version is available.
Closes #779.
Tested locally.

feat: add notification about available new version

---

package-lock.json
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/utils.ts

This reverts commit 9b1551e2086fb8e938ab47ab5124c281a86b15f4.
Reopens: https://github.com/Redocly/redocly-cli/pull/853

Revert "feat: add notification about available new version (#853)"

---

.github/CODEOWNERS
package.json
packages/cli/package.json
packages/core/package.json

Updated info about the code owners.

chore: update codeowners

---

packages/core/src/types/redocly-yaml.ts

improve `feature.openapi` types for config

fix: improve reference docs config options

---

packages/core/src/rules/common/__tests__/spec.test.ts
packages/core/src/rules/common/spec.ts
packages/core/src/rules/utils.ts

Validate types list in spec rule
closes https://github.com/Redocly/redocly-cli/issues/856

fix: validate types in spec rule

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

beta.114
- Added a new assertion [`notPattern`](./rules/custom-rules.md#notpattern-example) to the custom rules.

chore: v1.0.0-beta.114

---

docs/changelog.md

docs: improve the changelog

---

package-lock.json
package.json
packages/cli/package.json
packages/core/package.json
packages/core/src/types/oas2.ts
packages/core/src/types/oas3.ts

Remove x-meta validation as some people have custom data there.

hotfix: remove x-meta validation

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

v1.0.0-beta.118 release:
- feat: remove unused components in config (https://github.com/Redocly/redocly-cli/pull/960)
- feat: implemeent a special SpecExtension type (https://github.com/Redocly/redocly-cli/pull/964)
- feat: handle error if api does not exist (https://github.com/Redocly/redocly-cli/pull/887)
- feat: add media type examples override decorator (https://github.com/Redocly/redocly-cli/pull/897)
- fix: spec-components-invalid-map-name not applied for all examples ( https://github.com/Redocly/redocly-cli/pull/969)
- chore: change sortOrder logic (https://github.com/Redocly/redocly-cli/pull/972)

chore: v1.0.0-beta.118

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

v1.0.0-beta.119 release:
- [fix: spec rule error on extension additional properties (#978)

chore: v1.0.0-beta.119

---

package-lock.json
packages/cli/src/__tests__/commands/build-docs.test.ts
packages/cli/src/commands/build-docs/index.ts
packages/cli/src/commands/build-docs/types.ts
packages/cli/src/commands/build-docs/utils.ts
packages/cli/src/index.ts

chore: rename features.openapi to theme.openapi for build docs

---

packages/cli/src/__tests__/commands/push.test.ts
packages/cli/src/commands/push.ts

https://github.com/Redocly/workflows/issues/2498

fix: push destination parsing

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release v1.0.0-beta.122
- fix destination name validation (https://github.com/Redocly/redocly-cli/pull/1003)

chore: v1.0.0-beta.122

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

fix: add handling of absolute url path in ignore-file - https://github.com/Redocly/redocly-cli/pull/1014

chore: v1.0.0-beta.124

---

docs/changelog.md

Minor improvements to the changelog.
Noticed on: https://redocly.com/docs/cli/changelog/
n/a
n/a

chore: minor changelog improvements

---

docs/file-management.md

docs: fix typo

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package.json

Release of **v1.0.0-beta.127**:
- chore: add performance benchmark with hyperfine (https://github.com/Redocly/redocly-cli/pull/1089)
- docs: fix typo (https://github.com/Redocly/redocly-cli/pull/1095)
- fix: avoid different result depending on option arguments position (#1083)
- fix: incorrect error message on null schemas (#1068)
- fix: duplicated components created when referencing from components (#1080)
- feat: create update notifier for cli (https://github.com/Redocly/redocly-cli/pull/1090)
Related docs: https://github.com/Redocly/redocly-cli/pull/1084

chore: v1.0.0-beta.127

---

.github/CONTRIBUTING.md

We recently added `mlc` for link checking, but didn't add any information for contributors (internal or external) to be successful with it. This adds some notes to make it easier to get started.

Docs for link checker

---

docs/commands/build-docs.md
docs/commands/index.md
packages/cli/src/index.ts

Correction of the `build-docs` command description.

docs: update build-docs description

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release of v1.0.0-beta.128:
- https://github.com/Redocly/redocly-cli/pull/1100
- https://github.com/Redocly/redocly-cli/pull/1081
- https://github.com/Redocly/redocly-cli/pull/1062
- https://github.com/Redocly/redocly-cli/pull/1112
- https://github.com/Redocly/redocly-cli/pull/1115
Related docs:
- https://github.com/Redocly/redocly-cli/pull/1113
- https://github.com/Redocly/redocly-cli/pull/1118

chore: v1.0.0-beta.128

---

docs/resources/custom-plugins.md

Updates on preprocessors related to https://github.com/Redocly/redocly-cli/pull/1081
To merge along with the next release.

docs: update preprocessors description

---

docs/changelog.md

Update release date in changelog

chore: update release date in changelog

---

packages/cli/src/utils.ts

Clean organization id from telemetry

chore: clean organization id

---

Dockerfile
jest.config.js
packages/cli/src/__tests__/utils.test.ts
packages/cli/src/utils.ts

Improving data obfuscation (better files/folder/organizations/apis handling).
Detecting CI/Docker environments.
Tested on lab6

chore: improve data obfuscation

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release v1.0.0-beta.130: 
-  https://github.com/Redocly/redocly-cli/pull/1134
-  https://github.com/Redocly/redocly-cli/pull/1149
- https://github.com/Redocly/redocly-cli/pull/1150
- #1152
- https://github.com/Redocly/redocly-cli/pull/1143
- #1147
- https://github.com/Redocly/redocly-cli/pull/1153
Closes: https://github.com/Redocly/redocly-cli/issues/1148
Closes: https://github.com/Redocly/redocly-cli/issues/1146
Closes: https://github.com/Redocly/redocly-cli/issues/1073
Tested on Lab 6

chore: v1.0.0-beta.130

---

packages/cli/src/fetch-with-timeout.ts
packages/cli/src/update-version-notifier.ts
packages/cli/src/utils.ts

Handle aborted request in docker and remove redundant call in telemetry
Related: https://github.com/Redocly/redocly-cli/issues/1146

fix: handle aborted request in docker and remove redundant call

---

.github/workflows/smoke.yaml
__tests__/smoke/run-smoke.sh

Add Windows and NodeJS 20 smoke environments.
Further evolvement of https://github.com/Redocly/redocly-cli/pull/1166

chore: test smoke tests on Windows

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release v1.0.0-rc.2:
- Removed smoke pipeline run on merge
- Copypasting README.md for packages/cli instead of linking (NPM isn't tracking links correctly).
Note: Smokes in yarn envs are expected to fail

chore: v1.0.0-rc.2

---

.dockerignore
.github/workflows/performance.yaml
.github/workflows/smoke.yaml
Dockerfile
package.json
scripts/local-pack.sh
scripts/prepare-smoke.sh

- Fixes Yarn & Docker smoke tests
- Cleanup performance report

fix: yarn smoke tests

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release v1.0.0-rc.3:
- Fixed issue with publishing to dockerhub  https://github.com/Redocly/redocly-cli/pull/1182
- Added job for testing new version (no code changes) (https://github.com/Redocly/redocly-cli/pull/1184)
- Fixed smoke tests in Yarn and Docker environments (https://github.com/Redocly/redocly-cli/pull/1185)
Note: Smokes in yarn envs are expected to fail

chore: v1.0.0-rc.3

---

docs/changelog.md
package-lock.json
package.json
packages/cli/package.json
packages/core/package-lock.json
packages/core/package.json

Release v1.0.0
No code changes

chore: v1.0.0

---

.github/workflows/test-changeset.yaml

chore: without changeset

---

.github/workflows/test-changeset.yaml
package.json

chore: without changeset-3

---

.changeset/odd-panthers-kneel.md

Add changeset for https://github.com/Redocly/redocly-cli/pull/1187

chore: add changeset for pr-1187

---

scripts/post-changeset.js

Fixes release date stamp: https://github.com/Redocly/redocly-cli/pull/1213/files#diff-77f023b99d3d58008351d3e82fc06e6d06ba1bc2da9e41be6329b7fa4f419f05R11

chore: fix release date

---

.changeset/giant-pears-promise.md

Adding a changeset to prepare the release.

chore: add release changeset

---

.changeset/twenty-grapes-type.md
.github/workflows/smoke.yaml
__tests__/build-docs/build-docs-with-config-option/snapshot.js
__tests__/build-docs/simple-build-docs/snapshot.js
__tests__/commands.test.ts
__tests__/smoke/run-smoke.sh
package-lock.json
packages/cli/package.json

Fix smoke tests and update `redoc` to `v2.1`
https://github.com/Redocly/redocly-cli/issues/1240

fix: smoke tests and update redoc to v2.1

---

.changeset/twelve-seas-cough.md
package-lock.json
packages/cli/package.json

Add changeset for pr [#1234](https://github.com/Redocly/redocly-cli/pull/1234)
https://github.com/Redocly/redocly-cli/pull/1234

chore: add changeset for pr #1234

---

.changeset/hot-bulldogs-grow.md
.changeset/loud-forks-speak.md

Updating descriptions that will go into the changelog according to comments here: https://github.com/Redocly/redocly-cli/pull/1218

chore: update changeset descriptions

---

.changeset/hot-pens-fetch.md
.changeset/loud-forks-speak.md
.changeset/ten-carpets-fix.md
.changeset/twenty-grapes-type.md

Updating changeset description for the upcoming release: https://github.com/Redocly/redocly-cli/pull/1218

chore: update changeset description

---

.changeset/quick-poems-remain.md
package-lock.json
packages/cli/package.json

Updating the Redoc package to the latest version.

chore: update Redoc to v2.1.3

---

docs/rules/no-unused-components.md
docs/rules/operation-operationId.md
docs/rules/path-excludes-patterns.md
docs/rules/paths-kebab-case.md

A series of minor docs updates, spotted when working through a bunch of these pages to link to in social content.

Docs updates spotted when crafting Advent content

---

.github/pull_request_template.md
CONTRIBUTING.md

Streamlined the scripts usage section and updated the MR template.

chore: update contributing guide and the PR template

---

.changeset/lemon-onions-approve.md

Edit changeset to include openapi/cli package. 
https://github.com/Redocly/redocly-cli/pull/1412
n/a
n/a
No.

fix: fix changeset for no-required-schema-properties custom rule

---

docs/rules/no-required-schema-properties-undefined.md

Adding markdown file for changes related to https://github.com/Redocly/redocly-cli/pull/1412
https://github.com/Redocly/redocly-cli/pull/1412
n/a
n/a
n/a

docs: no-required-schema-properties-undefined markdown docs

---

.github/workflows/performance.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
benchmark/.gitignore
benchmark/README.md
benchmark/make-test-command.sh
benchmark/package.json

This PR adds performance overview of historical versions of Redocly CLI to release PRs (see the screenshot).
Also update node and slackapi/slack-github-action to the latest stable version.

chore: add historical performance benchmarking

---

docs/rules/no-required-schema-properties-undefined.md

It might be unclear that the rule is case sensitive. Added an example to illustrate that.
See the comment: https://github.com/Redocly/redocly-cli/issues/477#issuecomment-1943467337

docs: update the no-required-schema-properties-undefined rule description

---

.github/pull_request_template.md

Updated the PR template with instruction what to do when adding a new package.

chore: update the PR template

---

CONTRIBUTING.md

Described the release reverting flow.

docs: describe reverting a release

---

docs/rules/no-empty-servers.md

Fixes https://github.com/Redocly/redocly-cli/issues/1474

docs: fix the no-empty-servers slug typo

---

.changeset/cuddly-cheetahs-teach.md

Fix the description to match sentence case: https://github.com/Redocly/redocly-cli/blob/main/CONTRIBUTING.md#pull-request-guidelines

docs: fix changeset description to align with other changelog entries

---

docs/gsod/2024/proposal.md

I just noticed we should include background info to increase our chances of getting selected for GSOD. I updated the prop page accordingly.

Gsod prop context

---

package-lock.json
packages/core/package.json

chore: update core version in config

---

package-lock.json
packages/core/package.json

Bumped the Redocly config package version to 0.5.0.

chore: update @redocly/config version to 0.5.0

---

benchmark/package.json
package.json
scripts/local-pack.sh

Updating development scripts to be more convenient to use (+minor version update in the benchmark script).

chore: update scripts

---

docs/configuration/apis.md
docs/configuration/index.md

Updates the json-schema tag to reflect new format. 
This change impacts downstream documentation.
Previewed change by updating the tag in locally running version of downstream docs.

Updating json-schema tag

---

.changeset/chatty-tables-smell.md
__tests__/build-docs/simple-build-docs/snapshot.js
__tests__/commands.test.ts
package-lock.json
packages/cli/package.json

chore: upgrade Redoc to v2.1.5

---

benchmark/package.json

Added new Redocly CLI versions to historical benchmark tests.

chore: update benchmark setup

---

.github/workflows/deploy-s3-sandbox.yaml
.github/workflows/performance.yaml
.github/workflows/tests.yaml
CONTRIBUTING.md
jest.config.js
package.json

- Modified the test script to run all the tests
- Updated affected pipelines
- Removed tests from the `deploy-s3-sandbox` action as I don't think it makes too much sense there

chore: update test script and the corresponding pipelines

---

.changeset/silver-lizards-cover.md
package-lock.json
packages/core/package.json

Bumped the Redocly config package to current version.

chore: updgrade @redocly/config to v0.6.2

---

CONTRIBUTING.md
benchmark/package.json

Updated the Contributing guide + Performance benchmark versions list.

chore: update contributing guide

---

packages/core/src/types/arazzo.ts
packages/core/src/typings/arazzo.ts

Export more individual types for Arazzo in order to reuse them in the Spot package.

feat: export more individual types for arazzo

---

.changeset/test.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/docs-tests.yaml
.github/workflows/performance.yaml
CONTRIBUTING.md
benchmark/.gitignore
benchmark/chart.mjs
benchmark/package.json

Project maintenance chores:
- updated issue template and benchmark test.
- added changesets validation with Vale (as later they become part of the changelog).
- updated the contributing guide.
- improved benchmark output for release PRs.

chore: update issue template and add changesets validation, improve benchmark output

---

.changeset/happy-emus-repair.md
package-lock.json
packages/core/package.json

Updated @redocly/config to v0.10.1.

chore: update Redocly config to v0.10.1

---

.changeset/tough-shirts-invite.md
packages/core/src/config/config.ts

Apply configurable rules for arazzo specification.
Closes: https://github.com/Redocly/redocly-cli/issues/1718

fix: apply configurable rules for arazzo

---

.changeset/green-penguins-press.md
docs/guides/lint-arazzo.md
docs/rules/arazzo/criteria-unique.md
docs/rules/spot/no-actions-type-end.test.md
docs/rules/spot/no-criteria-xpath.md
packages/core/src/config/__tests__/__snapshots__/config-resolvers.test.ts.snap
packages/core/src/config/all.ts
packages/core/src/config/minimal.ts
packages/core/src/config/recommended-strict.ts
packages/core/src/config/recommended.ts
packages/core/src/rules/arazzo/__tests__/criteria-unique.test.ts
packages/core/src/rules/arazzo/__tests__/no-actions-type-end.test.ts
packages/core/src/rules/arazzo/__tests__/no-criteria-xpath.test.ts
packages/core/src/rules/arazzo/criteria-unique.ts
packages/core/src/rules/arazzo/index.ts
packages/core/src/rules/spot/no-actions-type-end.ts
packages/core/src/rules/spot/no-criteria-xpath.ts
packages/core/src/types/arazzo.ts
packages/core/src/types/redocly-yaml.ts
resources/arazzo.yaml

Adding Spot Arazzo rules and docs:

feat: adding spot arazzo rules

---

.changeset/hungry-drinks-grab.md
packages/core/src/config/config.ts
packages/core/src/rules/arazzo/criteria-unique.ts

Add additional checks to the rule.
Potential fix for cli version 1.25.0 errors related to arazzo rules run.

fix: changes in criteria-unique arazzo rule

---

.changeset/proud-poets-wave.md
package-lock.json
packages/core/package.json

Update redocly config version.

chore: update redocly config version

---

docs/commands/push.md

Fixes a broken link.
- Found from an alert.

docs: fix typo in url

---

.changeset/flat-cows-laugh.md
package-lock.json
packages/core/package.json

Updated redocly/config to v0.12.1

chore: updated redocly/config to v0.12.1

---

benchmark/chart.mjs
benchmark/make-test-command.sh
benchmark/package.json
jest.config.js
packages/core/src/bundle.ts
packages/core/src/resolve.ts

Updated benchmarks with the recent CLI versions.
Adjusted the benchmark command.
Bumped code coverage threshold.
Improved types and naming.

chore: update benchmarks, coverage threshold; improve types and names

---

.changeset/purple-moles-ring.md
__tests__/lint-config/config-structure/.redocly.yaml
package-lock.json
packages/core/package.json
packages/core/src/__tests__/lint.test.ts

Updated the Redocly config package to v0.15.0.

chore: update Redocly config to v0.15.0

---

.changeset/thick-wasps-shout.md
package-lock.json
packages/core/package.json

This PR updates version of @redocly/config in @redocly/openapi-core package.

chore: update redocly/config version

---

.changeset/real-chicken-cheat.md

Fixing changeset before the release: https://github.com/Redocly/redocly-cli/pull/1787#pullrequestreview-2404813900
Original changeset added [here](https://github.com/Redocly/redocly-cli/pull/1759).

chore: fix changeset

---

.changeset/large-pans-hunt.md
package-lock.json
packages/core/package.json

This PR updates version of @redocly/config in @redocly/openapi-core package.

chore: update reodcly-config version

---

docs/commands/generate-arazzo.md
docs/commands/index.md
docs/commands/respect.md

Add the command docs for respect and generate-arazzo (pending feature merge).

docs: add respect command docs

---

packages/respect-core/src/modules/__tests__/flow-runner/call-api-and-analyze-results.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
packages/respect-core/src/modules/flow-runner/call-api-and-analyze-results.ts
packages/respect-core/src/modules/flow-runner/run-step.ts
packages/respect-core/src/modules/flow-runner/runner.ts
packages/respect-core/src/types.ts

Refactor workflowId vs workflowName mix.
node)

chore: rename workflowId to workflowName and also targetWorkflow

---

__tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
__tests__/respect/outputs-access-syntax-variations/__snapshots__/outputs-access-syntax-variations.test.ts.snap
__tests__/respect/server-override-with-console-parameters/__snapshots__/server-override-with-console-parameters.test.ts.snap
__tests__/respect/severity-error-level/__snapshots__/severity-error-level.test.ts.snap
__tests__/respect/severity-off-level/__snapshots__/severity-off-level.test.ts.snap
__tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap
packages/respect-core/src/modules/flow-runner/runner.ts
packages/respect-core/src/utils/cli-outputs.ts

Verbose flag was lost. One-liner.

chore: verbose flag was lost for nested workflows

---

__tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
__tests__/respect/outputs-access-syntax-variations/__snapshots__/outputs-access-syntax-variations.test.ts.snap
__tests__/respect/reusable-components/__snapshots__/reusable-components.test.ts.snap
__tests__/respect/server-override-with-console-parameters/__snapshots__/server-override-with-console-parameters.test.ts.snap
__tests__/respect/severity-error-level/__snapshots__/severity-error-level.test.ts.snap
__tests__/respect/severity-off-level/__snapshots__/severity-off-level.test.ts.snap
__tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap
__tests__/respect/workflow-failure-actions/__snapshots__/workflow-failure-actions.test.ts.snap
__tests__/respect/workflow-success-actions/__snapshots__/workflow-success-actions.test.ts.snap
packages/respect-core/src/modules/__tests__/flow-runner/run-step.test.ts
packages/respect-core/src/modules/__tests__/flow-runner/runner/__snapshots__/create-workflow-runner.test.ts.snap
packages/respect-core/src/modules/__tests__/flow-runner/runner/create-workflow-runner.test.ts
packages/respect-core/src/modules/flow-runner/run-step.ts
packages/respect-core/src/modules/flow-runner/runner.ts
packages/respect-core/src/types.ts
packages/respect-core/src/utils/__tests__/cli-outputs.test.ts
packages/respect-core/src/utils/cli-outputs.ts

The output was too complex and was missing details (e.g. no failed steps when retry)

Simplify output format for nested/dependent workflows

---

.changeset/quick-zebras-design.md
package-lock.json
packages/core/package.json

Updated @redocly/config to v0.21.0.

chore: update @redocly/config to v0.21.0

---

.changeset/config.json
.github/CODEOWNERS

Fixed respect-core version to align with the other packages.

chore: fix respect-core version

---

benchmark/package.json
docs/rules/arazzo/parameters-unique.md
jest.config.js

Updated tests settings.
Fixed a typo in docs.

chore: update test settings and fix typo

---

.changeset/chatty-oranges-bow.md
package-lock.json
packages/cli/package.json
packages/core/package.json

Updated Redocly config to v0.22.0

chore: update @redocly/config

---

.changeset/spotty-maps-grab.md
docs/commands/generate-arazzo.md

- Update command option in examples.
- Removed changeset for docs update

docs: update command option in examples

---

docs/sidebars.yaml

Add respect commands to cli commands sidebar

docs(respect): add respect commands to cli commands sidebar

---

packages/cli/src/__tests__/utils.test.ts
packages/cli/src/utils/miscellaneous.ts

Internal changes to clearArgs.

chore: improve clearargs

---

benchmark/package.json

Update benchmark with 1.34 cli version

chore: update benchmark

---

__tests__/respect/consider-severity-in-next-step-execution/__snapshots__/consider-severity-in-next-step-execution.test.ts.snap
__tests__/respect/inputs-with-cli-and-env/__snapshots__/inputs-with-cli-and-env.test.ts.snap
__tests__/respect/mask-input-secrets/__snapshots__/mask-input-secrets.test.ts.snap
__tests__/respect/museum-api-with-errors.yaml
__tests__/respect/museum-api.yaml
__tests__/respect/outputs-access-syntax-variations/__snapshots__/outputs-access-syntax-variations.test.ts.snap
__tests__/respect/replacements/__snapshots__/replacements.test.ts.snap
__tests__/respect/reusable-components/__snapshots__/reusable-components.test.ts.snap
__tests__/respect/severity-error-level/__snapshots__/severity-error-level.test.ts.snap
__tests__/respect/severity-off-level/__snapshots__/severity-off-level.test.ts.snap
__tests__/respect/severity-warn-level/__snapshots__/severity-warn-level.test.ts.snap

Use redocly demo mock server as a target for respect e2e tests

chore: switch respect e2e target

---

.changeset/clever-spiders-design.md

feat: add changelog for the release

---

__tests__/respect/free-apis/__snapshots__/free-apis.test.ts.snap
__tests__/respect/free-apis/free.arazzo.yaml

Update condition & snapshot for the free api test due to response format changes.

fix(respect): update condition for free api due to response format changes

---

CONTRIBUTING.md
__tests__/smoke/pre-built/redoc.html
packages/cli/src/commands/build-docs/utils.ts
packages/core/package.json
packages/core/src/benchmark/benches/lint-with-many-rules.bench.ts
packages/core/src/config/config-resolvers.ts
packages/core/src/utils.ts
packages/respect-core/src/modules/config-parser/parse-request-body.ts

- Fixed node-specific packages imports in openapi-core
- Fixed dirname resolution
- Updated smoke snapshots

refactor: fix node packages import issues in openapi-core and dirname resolution

---

CONTRIBUTING.md

Add doc describing logging usage

docs: development guidelines

---

.changeset/format.js
.changeset/pre.json
.changeset/tame-pillows-flash.md
.changeset/unlucky-meals-hunt.md
.github/workflows/release.yaml

- Added changesets to v2
- Entered pre-release changeset mode (https://github.com/changesets/changesets/blob/main/docs/prereleases.md)
Related docs: https://github.com/Redocly/redocly-cli/pull/2049

chore: add changesets and enter pre-release mode

---

docs/@v2/index.md
scripts/post-changeset.js
scripts/write-release-message.js

Fixed post-release scripts using `require`.
Follow-up to https://github.com/Redocly/redocly-cli/pull/1988
Will be tested during release.

chore: fix post-release scripts

---

docs/@v1/changelog.md

Updated changelog accordingly to the latest changes in v1.
Original release PR: https://github.com/Redocly/redocly-cli/pull/2065

docs: update the v1 changelog

---

.github/workflows/smoke.yaml

Updated Yarn smoke tests with cache clean and retries due its instability.

fix: smoke test in yarn env

---

__tests__/respect/free-apis/free-apis.test.ts
package-lock.json

chore: resolve GHSA-x7hr-w5r2-h6wg

---

docs/@v2/custom-plugins/custom-decorators.md

Added a section with explanation of decorator execution order (kudos to @yarokon)
Resolves https://github.com/Redocly/redocly/issues/10603

docs: add explanation of decorators execution order

---

.changeset/happy-gorillas-march.md
package-lock.json
packages/cli/package.json
packages/core/package.json

Updated @redocly/config to v0.24.1.

chore: update Redocly config to v0.24.1

---

packages/core/src/rules/respect/x-security-schema-required-values.ts
packages/respect-core/src/modules/__tests__/flow-runner/validate-x-security-parameters.test.ts
packages/respect-core/src/modules/description-parser/get-operation-from-description.ts
packages/respect-core/src/modules/flow-runner/prepare-request.ts
packages/respect-core/src/modules/flow-runner/resolve-x-security-parameters.ts
packages/respect-core/src/modules/flow-runner/validate-x-security-parameters.ts

- Validate x-security values (check if values exist in runtime)
- Use `getSecurityParameters` function to get fetch parameters

feat(respect): validate x security

---

__tests__/respect/x-security-api-key-auth/__snapshots__/x-security-api-key-auth.test.ts.snap
__tests__/respect/x-security-api-key-auth/x-security-api-key-auth.arazzo.yaml
__tests__/respect/x-security-api-key-auth/x-security-api-key-auth.test.ts
__tests__/respect/x-security-basic-auth/__snapshots__/x-security-basic-auth.test.ts.snap
__tests__/respect/x-security-basic-auth/x-security-basic-auth.arazzo.yaml
__tests__/respect/x-security-basic-auth/x-security-basic-auth.test.ts
__tests__/respect/x-security-bearer-auth/__snapshots__/x-security-bearer-auth.test.ts.snap
__tests__/respect/x-security-bearer-auth/x-security-bearer-auth.arazzo.yaml
__tests__/respect/x-security-bearer-auth/x-security-bearer-auth.test.ts
__tests__/respect/x-security-oauth2-auth/__snapshots__/x-security-oauth2-auth.test.ts.snap
__tests__/respect/x-security-oauth2-auth/x-security-oauth2-auth.arazzo.yaml
__tests__/respect/x-security-oauth2-auth/x-security-oauth2-auth.test.ts
__tests__/respect/x-security-open-id-connect-auth/__snapshots__/x-security-open-id-connect-auth.test.ts.snap
__tests__/respect/x-security-open-id-connect-auth/x-security-open-id-connect-auth.arazzo.yaml
__tests__/respect/x-security-open-id-connect-auth/x-security-open-id-connect-auth.test.ts
__tests__/respect/x-security-resolve-scheme-name/__snapshots__/x-security-resolve-scheme-name.test.ts.snap
__tests__/respect/x-security-resolve-scheme-name/x-security-resolve-scheme-name.arazzo.yaml
__tests__/respect/x-security-resolve-scheme-name/x-security-resolve-scheme-name.test.ts
__tests__/respect/x-security-scheme-apply-order/__snapshots__/x-security-scheme-apply-order.test.ts.snap
__tests__/respect/x-security-scheme-apply-order/x-security-scheme-apply-order.arazzo.yaml
__tests__/respect/x-security-scheme-apply-order/x-security-scheme-apply-order.test.ts
packages/respect-core/src/utils/api-fetcher.ts

- Cover supported `x-security` auth types with e2e.
- fix: mask digest headers when format password is used

chore: cover supported x-security auth types with e2e

---

packages/respect-core/src/modules/__tests__/description-parser/resolve-x-security-parameters.ts.test.ts
packages/respect-core/src/modules/flow-runner/resolve-x-security-parameters.ts

fix: evaluate x-security values in step

fix: resolve x-security not evaluated values

---

packages/core/src/index.ts
packages/core/src/rules/respect/x-security-schema-required-values.ts
packages/respect-core/src/modules/__tests__/flow-runner/validate-x-security-parameters.test.ts
packages/respect-core/src/modules/config-parser/get-security-parameters.ts
packages/respect-core/src/modules/flow-runner/resolve-x-security-parameters.ts
packages/respect-core/src/modules/flow-runner/validate-x-security-parameters.ts

- Improved error handling for unsupported security schemes in x-security validation
- Updated types imports

chore(respect): improve error handling for unsupported security schemes

---

__tests__/respect/mask-input-secrets/__snapshots__/mask-input-secrets.test.ts.snap
__tests__/respect/mask-input-secrets/mask-input-secrets.arazzo.yaml
__tests__/respect/x-security-basic-auth/__snapshots__/x-security-basic-auth.test.ts.snap
__tests__/respect/x-security-bearer-auth/__snapshots__/x-security-bearer-auth.test.ts.snap
__tests__/respect/x-security-oauth2-auth/__snapshots__/x-security-oauth2-auth.test.ts.snap
__tests__/respect/x-security-on-workflow-level-merged-to-steps/__snapshots__/x-security-on-workflow-level-merged-to-steps.test.ts.snap
__tests__/respect/x-security-open-id-connect-auth/__snapshots__/x-security-open-id-connect-auth.test.ts.snap
__tests__/respect/x-security-resolve-scheme-name/__snapshots__/x-security-resolve-scheme-name.test.ts.snap
__tests__/respect/x-security-scheme-apply-order/__snapshots__/x-security-scheme-apply-order.test.ts.snap
packages/respect-core/src/modules/cli-output/mask-secrets.ts
packages/respect-core/src/modules/context-parser/get-security-parameters.ts

Mask only secret not the full string

feat: change respect mask function to hide only secrets

---

docs/@v1/guides/index.md
docs/@v1/index.md
docs/@v2/guides/index.md
docs/@v2/index.md

docs(all): replace outdated card format

---

.github/pull_request_template.md
benchmark/package.json

- Updated the PR template
- Updated perf. benchmark setup

chore: update pr template

---

packages/cli/src/auth/device-flow.ts

Added a timeout to all auth requests (3s).
Should resolve (potentially) https://github.com/Redocly/redocly-cli/issues/2155
Will require testing on the users' side.

chore: fix hanging when there is no response

---

.changeset/tasty-ligers-tan.md
package-lock.json
packages/cli/package.json
packages/respect-core/package.json

chore: bump form-data to 4.0.4 for v1

---

benchmark/package.json

- Fixed the CLI versions in the benchmark 
- Removed old v1 versions except for the last one

chore: update benchmark settings

---

.changeset/modern-fishes-float.md

docs: fix a changeset

---

docs/@v2/commands/generate-arazzo.md
docs/@v2/commands/respect.md

Added missing slugs. 
A follow up to https://github.com/Redocly/redocly-cli/pull/2220

docs: add missing slugs to respect-related commands

---

.changeset/empty-jars-turn.md
packages/respect-core/src/run.ts

fix: respect type for input and server

fix: respect type for input and server

---

.changeset/wild-owls-watch.md
package-lock.json
packages/core/package.json

Updated @redocly/config to v0.28.0.

chore: update redocly config to v0.28.0

---

.changeset/cute-chairs-pump.md
package-lock.json
packages/core/package.json

- Updated @redocly/config to v0.29.0
- Ran `npm auduit`

chore: update Redocly config to v0.29.0

---

.changeset/pink-rules-say.md
package-lock.json
packages/core/package.json

Update @redocly/config to v0.30.0

chore(deps): update @redocly/config to v0.30.0

---

package-lock.json
packages/cli/package.json
packages/respect-core/src/modules/__tests__/flow-runner/success-criteria/check-success-criteria.test.ts

Update undici to 6.21.3
https://github.com/Redocly/redocly-cli/pull/2095

chore: update undici to 6.21.3

---

.changeset/better-snails-occur.md
.changeset/brave-moments-mix.md
__tests__/respect/inputs-passed-to-step-target-workflow-and-remapped/__snapshots__/inputs-passed-to-step-target-workflow-and-remapped.test.ts.snap
__tests__/respect/inputs-passed-to-step-target-workflow-and-remapped/events.arazzo.yaml
__tests__/respect/inputs-passed-to-step-target-workflow-and-remapped/inputs-passed-to-step-target-workflow-and-remapped.arazzo.yaml
__tests__/respect/inputs-passed-to-step-target-workflow-and-remapped/inputs-passed-to-step-target-workflow-and-remapped.test.ts
__tests__/respect/inputs-passed-to-step-target-workflow/__snapshots__/inputs-passed-to-step-target-workflow.test.ts.snap
__tests__/respect/inputs-passed-to-step-target-workflow/events.arazzo.yaml
__tests__/respect/inputs-passed-to-step-target-workflow/inputs-passed-to-step-target-workflow.arazzo.yaml
__tests__/respect/inputs-passed-to-step-target-workflow/inputs-passed-to-step-target-workflow.test.ts
__tests__/respect/server-override-with-console-parameters/__snapshots__/server-override-with-console-parameters.test.ts.snap
package-lock.json
packages/respect-core/package.json
packages/respect-core/src/modules/__tests__/flow-runner/schema/schema-checker.test.ts
packages/respect-core/src/modules/flow-runner/context/set-public-workflows.ts
packages/respect-core/src/modules/flow-runner/run-step.ts
packages/respect-core/src/modules/flow-runner/runner.ts
packages/respect-core/src/modules/flow-runner/schema/schema-checker.ts

- fix: not reporting inputs resolution failed step with step use target workflowId.
- feat: change status code check message format
- feat: merge resolved inputs to targetWorkflowRef context and recalculate based on the scheme.

feat: resolve Respect inputs for targetWorkflowRef context
